### ISSUE TITLE
Nuget assembly reference quirks

### ISSUE THREAD

**Issue by nicemd** [filipw/dotnet-script#102]
It appears assembly referencing is messed up when referencing a nuget package that contains a reference to an existing assembly but located at another path.

This simple csx-script:

```
#r "nuget:AutoMapper,5.1.1"

using(var filestream = new FileStream("c:\\delete.me", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
}
```

Gives this compile time error:
```
error CS1503: Argument 2: cannot convert from 'System.IO.FileMode [c:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.FileSystem.Primitives.dll]' to 'System.IO.FileMode [C:\Users\nicla_000\.nuget\packages\System.IO.FileSystem.Primitives\4.0.1\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll]'
```

I tried to fix it myself but apparently I don't fully understand how assembly loading works with Roslyn.

**Comment by filipw** [comment]
the message is a bit misleading - I'll look into why it doesn't work properly. But you will need to include NetStandard.Library to make it work:

```
#r "nuget: NETStandard.Library,1.6.1"
#r "nuget:AutoMapper,5.1.1"

using(var filestream = new FileStream("c:\\delete.me", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
}
```

**Comment by filipw** [comment]
Had a quick look at this, and the reason for this behavior is that we have a conflict between the references needed for NET Core App (which is how scripts are executed) and the runtime references provided by Automapper as dependency.

The solution would be to not include the package dependencies that we can inherit automatically ourselves from the script runner runtime. I tested this and it works indeed, but it feels a bit dirty so I'll see if there is an alternative, better solution.

In the meantime the workaround with manually adding `NETStandard.Library` inline should do the trick.

**Comment by nicemd** [comment]
Thank you for investigating.

I tried the same with https://github.com/seesharper/csx and there it works. I took a quick look and @seesharper loads the references very differently, and it looks like it is then required to have the .NET sdk installed? (it runs ```dotnet nuget locals global-packages```).

**Comment by seesharper** [comment]
PR #100 basically adds the the same dependency handling to dotnet-script.

**Comment by seesharper** [comment]
The following script works with the 0.13.0 release 
```
#! "netcoreapp1.1"
#r "nuget:AutoMapper,5.1.1"

using(var filestream = new FileStream("c:\\delete.me", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
{
}
```
