### ISSUE TITLE
Help with using a netcore2.0 assembly?

### ISSUE THREAD

**Issue by pldmgg** [filipw/dotnet-script#114]
First, just wanted to say thank you for making the dotnet-script project. I think it'll really come in handy in the future.

So, I'm trying to use a netcoreapp2.0 assembly (OpenScraping: https://github.com/Microsoft/openscraping-lib-csharp) in a .csx file using dotnet script. But unfortunately, I'm receiving an error:

    PS C:\Users\pddomain\CSharpLocalTesting\OpenScrapingProject> dotnet script .\OpenScrapingTest_For_dotnet-script_cli.csx
    Script execution resulted in an exception.
    Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
       at Submission#0.<<Initialize>>d__0.MoveNext()
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
       at Submission#0.<Initialize>()
       at Submission#0.<Factory>(Object[] submissionArray)
       at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
    Could not load the specified file.

So I'm not sure exactly what is causing the issue, but I think that it could be one of the following (although I'm not sure which):

1) Maybe because dotnet script is a netcoreapp1.1, I can't use netcoreapp2.0 assemblies (not sure if this is a true statement)

2) Maybe because there's some kind of typename conflict resolution issue, but I'm not sure what specifically would be causing this

3) Maybe because it insists on using System.Runtime 4.1.1 from my GAC instead of my explicit reference to System.Runtime 4.3.0 in my $HOME\\.nuget\packages

4) Maybe there's some sort of reference syntax mistake I made in my .csx file

Here's all of the info related to my test project:

**Folder Structure**

```
OpenScrapingProject
|    ApiPortAnalysis.json
|    Notes.ps1
|    OpenScrapingTest_For_dotnet-script_cli.csx
|    OpenScrapingTest_For_scriptcs_cli.csx
|    OpenScrapingTest.csproj
|    project.json
|    project.lock.json
|    scriptcs_packages.config
|
└───.vscode
|    |   launch.json
└───bin
        └───Debug
            └───netcoreapp2.0
└───obj
    └───Debug
        └───netcoreapp2.0
|    |    |    OpenScrapingTest.AssemblyInfo.cs
|    |    |    ...
|    project.assets.json
|    OpenScrapingProject.csproj.nuget.cache
|    ...
└───scriptcs_packages
    └───HtmlAgilityPack.1.5.1
    └───Newtonsoft.json.10.0.3
    └───OpenScraping.1.0.1
    └───System.Runtime.4.3.0
    └───System.Runtime.Extensions.4.3.0
|   |    ScriptLibraries.csx
```

A few notes:
- I have a project.json AND a .csproj so that I can use "nuget restore" or "dotnet restore". Also, it seems like dotnet-script currently needs the project.json (otherwise, I noticed it just creates one on-the-fly in a temp folder, and it insists on targeting netcoreapp1.1 instead of 2.0, which is the main reason why I don't think it is able to handle netcoreapp2.0 assemblies)
- I have some scriptcs related stuff in there, because I've also been trying to test this with scriptcs (which results in a different error regarding the typename System.AppDomain not being available in System.Runtime.Extensions 4.1.0...which it isn't...it's in mscorlib, but I can't figure out how to force scriptcs to look in mscorlib...)
- I've installed System.Runtime 4.3.0 and System.Runtime.Extensions 4.3.0 in $HOME\\.nuget\packages as well as in my GAC (but it still insists on using 4.1.0 versions of each, which the OpenScraping assembly does not like)

Gist of launch.json:    https://gist.github.com/pldmgg/08619a540af6e216d0193d1cca1045ae

Gist of project.json:    https://gist.github.com/pldmgg/6d343a25e2bfe5f0b66e04ee060740ab

Gist of OpenScrapingtest.csproj:    https://gist.github.com/pldmgg/2c2f65359d0150c71ed81538b1d48ea5

Gist of OpenScrapingTest_For_dotnet-script_cli.csx:    https://gist.github.com/pldmgg/89cf205e56975fd2c64af9f6ca22d344

Gist of OpenScrapingTest_For_scriptcs_cli.csx:    https://gist.github.com/pldmgg/c118cdbf9226a94faad11fd1583ba6cb

**Comment by seesharper** [comment]
Dotnet-script is currently a netcoreapp1.1 and you will not be able to reference netstandard2.0/netcore20 packages. We are however in the process of moving to netcore20 as you can see in this branch. 

https://github.com/filipw/dotnet-script/tree/feature/netcore20

You can pull this branch and see if things look better there. Be aware that OmniSharp (Intellisense) will not be able to handle scripts in the context of a netcoreapp20 yet.

**Comment by pldmgg** [comment]
Awesome! So I just tried the feature branch and I'm getting the same error, which makes me think that while it would've never worked on the dotnet-script netcoreapp1.1 version, this error about System.Runtime 4.2.0 is unrelated...

Is my syntax for my System.Runtime reference in my OpenScrapingTest_For_dotnet-script_cli.csx not enough to force dotnet-script to use the nuget System.Runtime 4.3.0?  I also have System.Runtime 4.3.0 installed in my GAC alongside 4.1.0, but I still can't get it to use System.Runtime 4.3.0.

I feel like this is a newbie-type problem, but after researching for awhile, it always seems the answer is something like "rebuild the project in Visual Studio", but since I'm not using Visual Studio...I'm kinda stumped...

**Comment by pldmgg** [comment]
Finally got it working by doing the following:

On my system, I had the following installed (not sure if all are required, or just Net Core 2.0 SDK and Runtime) -

- .Net Core Runtime 2.1 Preview 1 (From: https://github.com/dotnet/core-setup#daily-builds)
- .Net Core SDK 2.0 (From: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md)
- .Net Core Runtime 2.0 (From: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md)
- .NET Core SDK 1.1.2 (From: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md)
- .Net Core Runtime 1.05 (From: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md)

1) Git clone https://github.com/filipw/dotnet-script/tree/feature/netcore20 and open it up in Visual Studio 2017 (must be version 15.3.3 or higher!)

2) In Visual Studio, for the Dotnet.Script project, NuGet install Microsoft.DotNet.InternalAbstractions 1.0.0. If I didn't do this before building the following would happen when I eventually went to run 'dotnet script .\OpenScrapingTestFor_dotnet-script_cli.csx' -
    PS C:\Users\pddomain\CSharpLocalTesting\OpenScrapingTest> dotnet script .\OpenScrapingTest_For_dotnet-script_cli.csx
    Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

3) Build the solution

4) Create the following file/folder structure in $HOME\.nuget\packages -

    dotnet.script <dir>
        0.13.0 <dir>
            Dotnet.Script.0.13.0.nupkg <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script\bin\Debug\Dotnet.Script.0.13.0.nupkg>
            Dotnet.Script.0.13.0.nuspec <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script\obj\Dotnet.Script.0.13.0.nuspec>
            lib <dir>
            netcoreapp2.0 <dir>
                Dotnet.Script.Core.dll <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script\bin\Debug\netcoreapp2.0
                Dotnet.Script.Core.pdb <file> <from same>
                dotnet-script.cmd <file> <from same>
                dotnet-script.deps.json <file> <from same>
                dotnet-script.dll <file> <from same>
                dotnet-script.pdb <file> <from same>
                dotnet-script.runtimeconfig.dev.json <file> <from same>
                dotnet-script.runtimeconfig.json <file> <from same>
                dotnet-script.sh <file> <from same>
                project.assets.json <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script\obj>

    dotnet.script.core <dir>
        0.13.0 <dir>
        Dotnet.Script.Core.0.13.0.nupkg <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Core\bin\Debug>
        Dotnet.Script.Core.0.13.0.nuspec <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Core\obj>
        lib <dir>
            netstandard2.0 <dir>
                Dotnet.Script.Core.deps.json <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Core\bin\Debug\netstandard2.0>
                Dotnet.Script.Core.dll <file> <from same>
                Dotnet.Script.Core.pdb <file> <from same>
                project.assets.json <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Core\obj>
                
    dotnet.script.extras <dir>
        0.13.0 <dir>
            Dotnet.Script.Extras.0.2.0.nupkg <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Extras\bin\Debug>
            Dotnet.Script.Extras.0.2.0.nuspec <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Extras\obj>
            lib <dir>
                netstandard2.0 <dir>
                    Dotnet.Script.Extras.AssemblyInfo.cs <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Extras\obj\Debug\netstandard2.0>
                    Dotnet.Script.Extras.AssemblyInfoInputs.cache <file> <from>
                    Dotnet.Script.Extras.csproj.CoreCompileInputs.cache <file> <from>
                    Dotnet.Script.Extras.csproj.FileListAbsolute.txt <file> <from>
                    Dotnet.Script.Extras.csprojResolveAssemblyReference.cache <file> <from>
                    Dotnet.Script.Extras.deps.json <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Extras\bin\Debug\netstandard2.0>
                    Dotnet.Script.Extras.dll <file> <from same>
                    Dotnet.Script.Extras.pdb <file> <from same>
                    project.assets.json <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script.Extras\obj>


5) Add dotnet-script.cmd (and dependencies) to a folder somewhere and add that folder to your system PATH and PowerShell $env:Path
I created the following file/folder structure under C:\Chocolatey\lib -

    dotnet-script <dir>
        Dotnet.Script.Core.dll <file> <from ...\Visual Studio 2017\Projects\dotnet-script-feature-netcore20\src\Dotnet.Script\bin\Debug\netcoreapp2.0
        Dotnet.Script.Core.pdb <file> <from same>
        dotnet-script.cmd <file> <from same>
        dotnet-script.deps.json <file> <from same>
        dotnet-script.dll <file> <from same>
        dotnet-script.pdb <file> <from same>
        dotnet-script.runtimeconfig.dev.json <file> <from same>
        dotnet-script.runtimeconfig.json <file> <from same>
        dotnet-script.sh <file> <from same>
        Microsoft.CodeAnalysis.CSharp.dll <file> <from $HOME\.nuget\packages\Microsoft.CodeAnalysis.CSharp.2.3.1\lib\netstandard1.3>
        Microsoft.CodeAnalysis.CSharp.Scripting.dll <file> <from $HOME\.nuget\packages\microsoft.codeanalysis.csharp.scripting\2.3.1\lib\netstandard1.3>    
        Microsoft.CodeAnalysis.dll <file> <from $HOME\.nuget\packages\Microsoft.CodeAnalysis.Common.2.3.1\lib\netstandard1.3>
        Microsoft.CodeAnalysis.Scripting.dll <file> <from $HOME\.nuget\packages\microsoft.codeanalysis.scripting.common\2.3.1\lib\netstandard1.3>
        Microsoft.DotNet.InternalAbstractions.dll <file> <from $HOME\.nuget\packages\Microsoft.DotNet.InternalAbstractions.1.0.0\lib\netstandard1.3>
        Microsoft.DotNet.ProjectModel.dll <file> <from $HOME\.nuget\packages\microsoft.dotnet.projectmodel\1.0.0-rc3-003121\lib\netstandard1.6>
        Microsoft.Extenstions.CommandLineUtils.dll <file> <from $HOME\.nuget\packages\microsoft.extensions.commandlineutils\1.1.0\lib\netstandard1.3>
        Microsoft.Extensions.DependencyInjection.Abstractions.dll <file> <from $HOME\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\1.1.0\lib\netstandard1.0>
        Microsoft.Extensions.DependencyModel.dll <file> <from $HOME\.nuget\packages\Microsoft.Extensions.DependencyModel.2.0.0\lib\netstandard1.6>
        Microsoft.Extensions.Logging.Abstractions.dll <file> <from $HOME\.nuget\packages\microsoft.extensions.logging.abstractions\1.1.1\lib\netstandard1.1>
        Microsoft.Extensions.Logging.dll <file> <from C:\Users\pddomain\.nuget\packages\microsoft.extensions.logging\1.1.1\lib\netstandard1.1>
        Newtonsoft.Json.dll <file> <from C:\Users\pddomain\.nuget\packages\Newtonsoft.Json\10.0.3\lib\netstandard1.3>

6) Finally, cd to your OpenScrapingTest Project root folder and -
    PS C:\Users\pddomain\CSharpLocalTesting\OpenScrapingTest> dotnet script .\OpenScrapingTest_For_dotnet-script_cli.csx
    Article title
    ----------------------------
    {
    "title": "Article title",
    "body": "Article contents"
    }

**Comment by seesharper** [comment]
Thanks a lot for taking your time to investigate. 
We will try to replicate this scenario.

**Comment by seesharper** [comment]
Tested with 0.15.0 and seems to work just fine
