### ISSUE TITLE
Homebrew (Mac)

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#118]
We should look into creating a "tap" for `dotnet-script`

https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by filipw** [comment]
FWIW, here is what we do in scriptcs:

 - https://github.com/scriptcs/scriptcs/blob/dev/build_brew.sh
 - https://github.com/Homebrew/homebrew-core/blob/master/Formula/scriptcs.rb

**Comment by seesharper** [comment]
Closing this for now since we have a installation script and now also provides installation as a global tool. We can always open this later if we decide to support Homebrew
