### ISSUE TITLE
Pass the script path to scripts

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#121]
I was thinking that it would be quite useful to have access to the script path (main script) from within the script itself.
I see that ScriptCs provides this through `Env.ScriptPath`  which is great apart from the fact that OmniSharp does not recognize the `Env` type and squiggly lines appears in VS Code.

A simple and possible naive solution might be to pass the path of the main script as the first argument to the script. I guess that would be the `WorkingDirectory`  from the `ScriptContext` class or something like that.

**Comment by seesharper** [comment]
Another and far more involved solution would be to somehow provide the metadata for `Env` to OmniSharp and then in Dotnet-Script we can subclass the `CommandLineScriptGlobals`  and provide the 'Env' from there. 

When I think about it we could actually provide a NuGet package for the scripting environment. This would be an empty assembly containing just the `Env` interface and we implement that interface in the subclassed `CommandLineScriptGlobals` for marshaling between the script and the host.

```
#r "nuget:Dotnet.Script.Environment, 1.0.0"
Console.WriteLine(Env.ScriptPath);
```
Just thinking out loud here :)

**Comment by seesharper** [comment]
It would probably be best to align with `Env` in ScriptCs. If we at some point make this a "global" within OmniSharp, both engines will benefit from it.

**Comment by filipw** [comment]
Yes this is useful because the current directory cannot be trusted and I also thought about it.

But I think this should be solved at the Roslyn. `csi` doesn't have it and it is somewhat limiting already from what I experienced. IMHO it should be bundled into `CommandLineScriptGlobals`, we can just PR it in there.

**Comment by filipw** [comment]
it's even up for grabs :) https://github.com/dotnet/roslyn/issues/5979

**Comment by adamralph** [comment]
👍 for solving this in Roslyn so it's available to all runners which implement the standard globals type.

**Comment by seesharper** [comment]
So we are talking about a `Script` class exposed as a property on `CommandLineScriptGlobals` then?

**Comment by filipw** [comment]
yes, a semantic equivalent to `ScriptEnvironment` that hangs off `CommandLineScriptGlobals`.

**Comment by filipw** [comment]
it's a bit slower to do it in Roslyn, but we solved debugging there, we will solve this too 😄 And it means we are "pushing" some sort of a reasonable standard for scripting

**Comment by seesharper** [comment]
Guess its time to fork Roslyn then :) Do you know if changes should be made on master or do they have a preferred dev branch for contributions?

**Comment by filipw** [comment]
`master`

**Comment by seesharper** [comment]
@filipw @adamralph 
I've started on a PR for this 
https://github.com/dotnet/roslyn/pull/22040

**Comment by seesharper** [comment]
@filipw , @adamralph 

The super simple approach to this is to create a static method like this.
``` 
using System.Runtime.CompilerServices;

public static string GetScriptPath([CallerFilePath] string path = null)
{
    return path;
}
``` 

From anywhere in your script(s), you can simply do 

```
var pathToScript = GetPathToScript();
``` 

IMHO, problem solved :)

**Comment by adamralph** [comment]
Sounds like a NuGet package to me! 😉

**Comment by seesharper** [comment]
The worlds smallest NuGet package, but yes, it certainly could be :)

**Comment by filipw** [comment]
nice! 
even smaller 😄  `public static string GetScriptPath([CallerFilePath] string path = null) => path;`

**Comment by seesharper** [comment]
I am actually tempted to accept this as a solution and close this issue after we document this nice little workaround in the readme?

**Comment by filipw** [comment]
yes in fact within a script, it can be internal just: `static string GetScriptPath([CallerFilePath] string path = null) => path;
I am all for it, for the time being it's absolutely OK

**Comment by adamralph** [comment]
:+1: to that as a solution.

**Comment by seesharper** [comment]
Closing this as we have documented how to do this here #137

**Comment by robertmclaws** [comment]
Any chance that you folks could figure out a way to pull this into the context of the executing script, so we don't have to have an extra file just for this? Thanks!
