### ISSUE TITLE
Passing arguments to dotnet script at the command line doesn't work.

### ISSUE THREAD

**Issue by djohnst10** [filipw/dotnet-script#135]
I have the following foo.csx file (from the example in [README.md](https://github.com/filipw/dotnet-script/blob/master/README.md)):

```C#
#! "netcoreapp1.1"
#r "nuget:NetStandard.Library,1.6.1"

foreach (var arg in Args)
{
    Console.WriteLine(arg);
}
```
When I try to run dotnet script at the command line I see the following:
```shell
>  dotnet script .\foo.csx -- arg1 arg2 arg3
Couldn't find file '.\foo.csx -- arg1 arg2 arg3'
```
I've tried this from cmd and PowerShell.

I am running version 0.13.0 of dotnet-script on Windows 10.

**Comment by seesharper** [comment]
Thanks for reporting this. Confirmed as a bug.
Looking into it.
