### ISSUE TITLE
Install script on *nix 

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#145]
I've been thinking that we might provide a simple install script on *nix platforms.

This script would do the following

* Download the zip from GitHub releases into a temp folder
* Extract the files into the lib folder such as `/usr/local/lib/dotnet-script
* Create a symlink `dotnet-script -> /usr/local/lib/dotnet-script/dotnet-script.sh`
* Remove the temp folder

The documentation for installing on *nix would be as simple as 

```
bash <(curl -s https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install-dotnet-script.sh)
```
> Note: The location of the install script is just an example here. We might put it on the actual GitHub release. 

This way we don't have to fight with `brew` on Mac and/or `apt` on Linux.

Links 

https://stackoverflow.com/questions/5735666/execute-bash-script-from-url

**Comment by filipw** [comment]
done
