### ISSUE TITLE
Hiding script.csproj

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#149]
We generate `script.csproj` at the moment (here - https://github.com/filipw/dotnet-script/blob/0.14.0/src/Dotnet.Script.DependencyModel/ProjectSystem/ScriptProjectProvider.cs#L70). 

@seesharper should we put in a hidden folder instead of the current script folder? It would seem cleaner, not sure if this would break something but I don't think the location matters, if it's known? For example scriptcs uses `.scriptcs_cache` for its own hidden cache.

**Comment by seesharper** [comment]
It does not really matter where the location is and although it does not break anything to change the location, it would be best if `OmniSharp` and `Dotnet.Script` shares this location as they read the same `project.assets.json` file to get the `DependencyContext`. They don't have to, but we can save a restore here and there.

> should we put in a hidden folder instead of the current script folder?

We does not really put it in the current script folder. We put it inside the temp folder in a directory structure that reflects the original path. 

So if the script path is 
```
C:\ScriptDemo\HelloWorld.csx
```

The generated csproj file gets created in 

```
C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo
```

So although it isn't hidden per se, it is not created inside the current script folder :)

If we decide to change this in the future, we should align this with the version of `Dotnet.Script.DependencyModel` that we reference from OmniSharp. 

For the time being, I would propose that we leave it as is for now until the next version of `OmniSharp` is shipped. 

This behaviour is not new in `Dotnet.Script.DependencyModel`. We did it exactly the same way in `Dotnet.Script.NuGetMetadataResolver` which is what OmniSharp.Script currently references.

**Comment by filipw** [comment]
Oh I see what happens. You are right the code does that, however it was misbehaving on UNC paths which is my setup 😄
