### ISSUE TITLE
Consider using AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#161]
When resolving platform assemblies, we should consider using [AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")](http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/Hosting/Resolvers/RuntimeMetadataReferenceResolver.cs,184).

This will help us reliably locate the implementation assemblies on CoreCLR.

**Comment by seesharper** [comment]
Closing this since we now query the AssemblyLoadContext before adding a reference.

https://github.com/filipw/dotnet-script/pull/261

From The PR 

> So the approach taken is that we now inherit "on demand" meaning that when we load a assembly reference from the script dependency context, we will now check if the assembly is already loaded by the host. If its already loaded we skip the reference from the script dependency context, otherwise we load it. This should also fix the scenario when we run as netcoreapp2.0 where we only have the ``` netcoreapp2.1 sdk installed.
