### ISSUE TITLE
Issues with Globals Type in .NET Core 2.0 intellisense

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#162]
Repro steps:

Just access a property of the globals object:

```
#! "netcoreapp2.0"
var x = Args.FirstOrDefault();
```

**Expected Result**

No Error.

**Actual Result**

<img width="625" alt="screen shot 2017-11-02 at 14 28 21" src="https://user-images.githubusercontent.com/1710369/32328383-1cf92438-bfda-11e7-9d40-ce7e970ddc3c.png">

Note that Linq itself works correctly. For example, the following code works fine:
```
#! "netcoreapp2.0"
var x = new List<string> {"a"};
var y = x.FirstOrDefault();
```

**Comment by seesharper** [comment]
Are you on the latest C# extension  in Vs Code?
Remember that the one currently released uses project.json behind the scenes and could easily choke on netcoreapp.20

**Comment by seesharper** [comment]
The following should be okay 

```
#! "netcoreapp1.1"
#r "nuget:NetStandard.Library,1.6.1"

var x = Args.FirstOrDefault();
```

**Comment by filipw** [comment]
Yeah this is on the latest release. The above that you posted works indeed, but of course it impacts the resolution process, and I explicitly would like .NET Core 2.0 resolution to be in place.

The generated `script.csproj` is like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
</Project>
```

I suspect it has something to do with the fact that the injected reference to script globals type is coming directly from `net46` OmniSharp runtime.

**Comment by seesharper** [comment]
There is something strange her.
Just installed the latest extension 
https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.13.0-beta4

The Omnisharp log still outputs 

```
[info]: OmniSharp.Script.ScriptProjectSystem
        Found script runtime context '.NETCoreApp' for 'C:\Users\bri\AppData\Local\Temp\scripts\c\Github\scriptdemo\project.json'.
```

**Comment by seesharper** [comment]
It might look like the extension did not install properly. Can't get rid of the "Reload" button

![image](https://user-images.githubusercontent.com/1034073/32331109-545cdc28-bfe2-11e7-88c9-b1c1212aa2ca.png)

**Comment by filipw** [comment]
oops sorry I stripped down my repro too far 😀 Here is a correct one:

```
#! "netcoreapp2.0"
#r "nuget: Newtonsoft.Json, 10.0.3"
var x = Args.FirstOrDefault();
```

So JSON.NET messed it up in this case.

**Comment by seesharper** [comment]
> I suspect it has something to do with the fact that the injected reference to script globals type is coming directly from net46 OmniSharp runtime.

That is certainly an issue, although I am not sure why referencing JSON.NET causes the error.

This works though :)

```
var x = ((IList<string>)Args).FirstOrDefault();
```

**Comment by seesharper** [comment]
We should probably provide the `CommansLineScriptGlobals` and `InteractiveScriptGlobals` from `Dotnet.Script.DependencyModel` so that we reference the types according to the target framework

**Comment by seesharper** [comment]
Fixed by #169

**Comment by seesharper** [comment]
Closed the wrong issue :)

**Comment by seesharper** [comment]
@filipw Can you retry this on your end. Seems to be fixed by https://github.com/filipw/dotnet-script/issues/181

**Comment by seesharper** [comment]
@filipw This seem to work just fine on my machine 😄

**Comment by filipw** [comment]
Fixed!
