### ISSUE TITLE
Publish a tools NuGet package

### ISSUE THREAD

**Issue by adamralph** [filipw/dotnet-script#164]
I.e. with all the bits in `tools/` in the NuGet package. This would allow me to bootstrap `dotnet-script` locally and use it run build scripts, instead of using `csi.exe` inside `Microsoft.Net.Compilers`.

**Comment by adamralph** [comment]
OK I just found https://www.nuget.org/packages/dotnet.script - but it's not a tools package. `dotnet-script.cmd` and `dotnet-script.sh` are in `content/` and the assemblies are in `lib/`. What is the purpose of this package?

**Comment by adamralph** [comment]
I tried to use https://www.nuget.org/packages/dotnet.script as-is, but that doesn't work, since it's not self contained (it has deps on other packages). For my use case, a tools package is required.

**Comment by filipw** [comment]
> What is the purpose of this package?

it can be installed as `DotNetCliToolsReference`.
Anyway, a tools package could also be published, but why not bootstrap from Github directly (i.e. like this repo does to build itself)

**Comment by adamralph** [comment]
I want a local bootstrap only. I.e. I don't want to run the ps1 since that puts stuff in ProgramData, changes PATH, etc.

**Comment by filipw** [comment]
You can never boostrap a dotnet CLI extension locally only, unless you use a `DotNetCliToolsReference`. So the easiest is to just add it to your project, or if you have an old style csproj, then create another one with just a single `DotNetCliToolsReference` in it. This way you can easily bootstrap locally.

With a tools package you'd need to run `dotnet exec dotnet-script.dll` or at least `dotnet-script.cmd` instead of a proper CLI integration, which is not ideal.

On another note, you don't need to use CSI from `Microsoft.Net.Compilers` - if you take a dependency on MsBuild, CSI is always installed with MsBuild Tools anyway, so there is no need to install anything.

**Comment by adamralph** [comment]
> With a tools package you'd need to run dotnet exec dotnet-script.dll or at least dotnet-script.cmd instead of a proper CLI integration, which is not ideal.

It's not ideal, but that's what I want to do. I don't want to install it as `DotNetCliToolsReference` in a project since that doesn't make sense in the context of using it as a runner for building an entire solution, or for running other targets which may not even touch the solution. Or even for building stuff which doesn't have a csproj, such as `simple-targets-csx`.

> On another note, you don't need to use CSI from Microsoft.Net.Compilers - if you take a dependency on MsBuild, CSI is always installed with MsBuild Tools anyway, so there is no need to install anything.

The problem then is that I have to use something like `vswhere` to locate it. I prefer to bootstrap the runner locally in a deterministic place.

FYI, I [spiked using the chocolatey package as-is](https://github.com/adamralph/liteguard/pull/156). It works but it's quite hacky because it needs a separate `packages.choco.config` and I have to use `-DirectDownload` and `-NoCache` to avoid polluting the NuGet cache (this would be less of an issue if the choco and Nuget packages had different names but I think I'd still prefer to not to pollute the NuGet cahce). I think it's probably too hacky to merge. I'd prefer the tools package in NuGet.

**Comment by filipw** [comment]
OK, then let's create a `dotnet.script.runner` package, that would be a choco package copy, on nuget then.

**Comment by adamralph** [comment]
👍 sounds good.

I assume it won't be an _exact_ copy? The choco package seems to have a choco-specific folder structure.

**Comment by seesharper** [comment]
I you only need to get it installed locally into a folder you could use something like this 
https://github.com/filipw/dotnet-script/blob/master/build/install-dotnet-script.ps1

I think we should be a little careful with introducing new package names that can potentially confuse the user. In hindsight it might have been better to name the choco package `Dotnet-Script` and the NuGet packages `Dotnet.Script....`

**Comment by adamralph** [comment]
Yeah, that would work, but NuGet also comes with it's own cache, which is nice for coding on a plane (which I do a lot of).

Having said that, I'm already rolling my own cache for nuget.exe, and when dotnet-script gets support for packages containing csx, then I'll only be using nuget.exe to get dotnet-script, so I may as well just get dotnet-script directly and use my hand-rolled cache for that instead, and whether I grab dotnet-script from a tools package or from a GH release doesn't make much difference. Based on that, I'm happy to withdraw this issue, unless you still see value in it for other reasons. 😄

**Comment by seesharper** [comment]
@adamralph  Great
I think we are aiming in on the rough outline of packages with csx files so that should not be to far away. 
That taken into consideration, I'll rather not put another package out. Hope that is okay with you for the moment :)

**Comment by adamralph** [comment]
Absolutely. Thanks for asking the right questions and making me think it through. 😃

**Comment by adamralph** [comment]
FYI I pushed a [new package to wrap command invocation](https://www.nuget.org/packages/SimpleExec/) and [switched to it in my dotnet-script spike for LiteGuard](https://github.com/adamralph/liteguard/commit/ddc4b55adea2e7bf1ae92917a7f0399acda1138a#diff-07b46f83cb087dc75f9af3ca504ff599R1) and it works perfectly!
