### ISSUE TITLE
assembly load issue with simple script using System.Data.SqlClient

### ISSUE THREAD

**Issue by softeering** [filipw/dotnet-script#166]
Hi,

I'm facing an issue while trying to execute the following script which loads the System.Data.SqlClient nuget package:
```csharp
#! "netcoreapp2.0"
#r "nuget:NetStandard.Library,2.0.0"
#r "nuget:System.Data.SqlClient, 4.4.0"

using System.Data.SqlClient;

using (var connection = new SqlConnection(""))
{
	connection.Open();
	Console.WriteLine("Hello world!");
}
```

This seems to be loading the default implementation of System.Data.SqlClient instead of the one specific to the platform.
The error message is:

```
PS C:\Temp\tdstest> dotnet script .\helloworld.csx
Script execution resulted in an exception.
System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Temp\tdstest\helloworld.csx:line 7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
System.Data.SqlClient is not supported on this platform.
```

Any idea if and how I could workaround this?

Thanks in advance

**Comment by filipw** [comment]
@seesharper looks like we resolve to `.nuget\packages\system.data.sqlclient\4.4.0\lib\netstandard2.0\System.Data.SqlClient.dll` instead of `.nuget\packages\system.data.sqlclient\4.4.0\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll`?

**Comment by seesharper** [comment]
I’ll have a look

**Comment by seesharper** [comment]
![image](https://user-images.githubusercontent.com/1034073/32460613-a5f10740-c333-11e7-9484-7dfcd9011b11.png)

We pick the wrong `RuntimeAssemblyGroup` here 

Looking into it

**Comment by softeering** [comment]
Awesome guys, thanks for the support. 
Let me know if I can be of any help

**Comment by seesharper** [comment]
Think I got it now. I just need to create a test for this. Think I am going to create a database in Azure so that we can verify SQL Server connections.

**Comment by adamralph** [comment]
FWIW, another option is to use localdb.

**Comment by seesharper** [comment]
Giving Azure a try so that we can test from Mac OS and Linux :)

**Comment by adamralph** [comment]
Right, I guess SQL Server on Mac isn't a thing. Dunno if localdb on Linux is a thing.

**Comment by seesharper** [comment]
Question is what to do with the connection string. Secure variables are not decoded by Appveyor for pull requests

**Comment by seesharper** [comment]
I am going with a read only user and simply expose the connection string

**Comment by seesharper** [comment]
@filipw You are welcome to take a look here. I've created a branch for this `bug/issue166` 

It works if the target framework is set to `netcoreapp1.1`
```
#! "netcoreapp1.1"
#r "nuget:NetStandard.Library,2.0.0"
#r "nuget:System.Data.SqlClient, 4.4.0"

using System.Data.SqlClient;
```

Setting it to `netcoreapp2.0` fails saying it cannot load one of the dependencies.

**Comment by seesharper** [comment]
Might be releated to `inheritedAssemblyNames`

**Comment by seesharper** [comment]
Finally got it. We must not add inherited assembly names if they are resolved as a runtime dependency. 
If the script dependency context brings in a dependency, we must use that rather than the inherited assembly name. Otherwise we might get in trouble with versions as the case is here. 
Fixing

**Comment by filipw** [comment]
whoa.. great catch!  👑
makes total sense too

**Comment by softeering** [comment]
Thanks for the quick support guys. I will test this in my netcoreapp2.0 as soon as I can update the nuget packages there.
Will keep you posted on the outcome.

**Comment by softeering** [comment]
Out of curiosity, do you have any ETA about when the new NuGet packages will be available?

Thanks

**Comment by filipw** [comment]
we have been releasing 1-2 times a month, so I'd say we can push it out in a few days

**Comment by softeering** [comment]
Thanks
