### ISSUE TITLE
Idea dotnet-notebook

### ISSUE THREAD

**Issue by nietras** [filipw/dotnet-script#171]
Wouldn't be awesome to combine `dotnet-script` with Markdown to create something like a Jupyter Notebook, but without the awful Python (incl. the Jupyter requirement for Python), for dotnet and **in** dotnet. Probably a completely different project, but perhaps people here have already had this idea?

Yes, I know there exists projects for getting C# on Jupyter... but looking for something self contained.

**Comment by atifaziz** [comment]
@nietras Have you looked at [Xamarin Workbooks](https://developer.xamarin.com/guides/cross-platform/workbooks/)?

> Xamarin Workbooks provide a blend of documentation and code that is perfect for experimentation, learning, and creating guides and teaching aids.

**Comment by nietras** [comment]
@atifaziz ah yes, but this doesn't run .NET Core as far as I understood, is that correct?

**Comment by nietras** [comment]
Wait, yes it does. Maybe that has changed...
```
Console (.NET Core) | Supported on Mac and Windows
```
Well, ok then, I guess everything already exists. 😄

**Comment by nietras** [comment]
Only thing is it doesn't support writing markdown directly it seems. Which is annoying.
