### ISSUE TITLE
dotnet script init no longer appears to be a command

### ISSUE THREAD

**Issue by runxc1** [filipw/dotnet-script#174]
In the documentation for setting up your environment it tells you to run the command 
`dotnet script init`

however the output from that command in an empty folder is 

> Couldn't find file 'init'

**Comment by seesharper** [comment]
What version of dotnet-script? 
What operating system?

**Comment by runxc1** [comment]
Thanks,  ran the command and it looks like I had to versions in my path from when I tried it out months ago

**Comment by seesharper** [comment]
Great 👍
