### ISSUE TITLE
Building Chocolatey package fails when running `build.ps1` from project root

### ISSUE THREAD

**Issue by andmos** [filipw/dotnet-script#177]
Building the project from `.\build.ps1` in project root fails with 
`Could not find a part of the path 'C:\Code\Git\dotnet-script\Chocolatey\tools\LICENSE.TXT'.`. 
Solution is to run from `build\` folder, `..\build.ps1`. @seesharper knows this, just making a note of it here :)

**Comment by filipw** [comment]
ugh I saw this before too and thought I was being stupid 😄

**Comment by seesharper** [comment]
I'm fixing this in the script-packages branch. I need to to some minor changes there anyway
