### ISSUE TITLE
Document using dotnet-script with piping

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#183]
Came across a pretty interesting use case for `dotnet-script` today. I was asked by @andmos if we could pipe something into `dotnet-script` 

Something like 
```
echo "This is some text" | dotnet script UpperCase.csx 
```

This is what we came up with (`UpperCase.csx`)

```
#! "netcoreapp2.0"
#r "nuget: NetStandard.Library, 2.0.0"

using (var streamReader = new StreamReader(Console.OpenStandardInput()))
{    
    Write(streamReader.ReadToEnd().ToUpper()); 
}
```

Then we can do 

```
$ echo "This is some text" | dotnet script UpperCase.csx
THIS IS SOME TEXT
```

@filipw Although this is not specific to `dotnet-script` , it might be a very useful scenario to mention in the documentation. What do you think? Pretty nice, huh? 😄

**Comment by andmos** [comment]
For most *NIX scripting guys pipes and stdout redirects is a large part of life, so it was pretty cool that this worked out-of-the-box with dotnet-script and the standard `Console.OpenStandardInput()` methods. Makes another great tool in the toolkit!
