### ISSUE TITLE
#r is not loaded from #load .csx file

### ISSUE THREAD

**Issue by SlowLogicBoy** [filipw/dotnet-script#189]
Hey,

I have:
```
C:.
│   helloworld.csx
│   omnisharp.json
│
├───.vscode
│       launch.json
│
├───AnotherFolder
│       Dependencies.csx
│
└───SomeFolder
        Scripts.csx
```
Now `Dependencies.csx` contains:
```CSharp
#r "nuget: Newtonsoft.Json,10.0.3"
using Newtonsoft.Json;
Console.WriteLine(JsonConvert.SerializeObject("String"));
```
And `Scripts.csx`:
```CSharp
#load "../AnotherFolder/Dependencies.csx"
using Newtonsoft.Json;
Console.WriteLine(JsonConvert.SerializeObject("String"));
```
And `Scripts.csx` doesn't load `nuget: Newtonsoft.Json,10.0.3` unless I put nuget loading in `Scripts.csx` file. Is there a way to load references that are referenced in other `.csx` files?

```
.\New folder\AnotherFolder\Dependencies.csx(5,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
.\New folder\SomeFolder\Scripts.csx(6,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
.\New folder\AnotherFolder\Dependencies.csx(7,19): error CS0103: The name 'JsonConvert' does not exist in the current context
.\New folder\SomeFolder\Scripts.csx(8,19): error CS0103: The name 'JsonConvert' does not exist in the current context
Script compilation failed due to one or more errors.
```

EDIT:
* I noticed that if both files are in the same folder, it works.
* If I move `Scripts.csx` to the root and `Dependencies.csx` leave in `AnotherFolder` it also works.
* But if I move `Scripts.csx` to `SomeFolder`, it no longer works, I guess this is something with `../` part in  `#load "../AnotherFolder/Dependencies.csx"`
* Even if I don't use `Json.Net` in `Scripts.csx` I get the same error, since `Dependencies.csx` can't load it.
* If I don't reference any nuget packages in `Dependencies.csx` just let's say I create `SomeMethod()` it works in `Scripts.csx`

**Comment by filipw** [comment]
This is a different manifestation of the same problem as mentioned here - https://github.com/filipw/dotnet-script/pull/179#discussion_r152201758.
At the moment, the inline nuget references are only parsed once, at startup. They are also not parsed via `#load`. 

Having "self-contained" resolvers would solve that.

**Comment by SlowLogicBoy** [comment]
Any plans when this will be done? 
Since I think this is the single thing that keeps me from moving from other `.csx` "runners".

**Comment by seesharper** [comment]
@SlowLogicBoy What script is it that you are executing here? `helloworld.csx` ?

**Comment by SlowLogicBoy** [comment]
`Scripts.csx`

**Comment by seesharper** [comment]
Okay, that should explain the behavior that you are seeing. When we look for script files to be included in the "script context", we look for files in the same folder as the target script (`scripts.csx`) and in all subfolders. That means that if you put your file one level up we will also span `AnotherFolder` and hence resolve the NuGet package inside `dependencies.csx`

**Comment by SlowLogicBoy** [comment]
@seesharper, do you think this is a valid case to make it work or this is intended and I should rearrange my scripts?

**Comment by adamralph** [comment]
Does it work as it is with other runners? E.g. csi.exe?

**Comment by seesharper** [comment]
Given that the folder structure sort of defines the "script project", it would make most sense to put your `scriptcs.csx` file in the "root" folder

**Comment by SlowLogicBoy** [comment]
@adamralph, it does, I just need to #r "full path to dll" instead of nuget.

**Comment by seesharper** [comment]
@adamralph There's no "NuGet" in csi.exe, yet :)

**Comment by adamralph** [comment]
Oops, silly me. I made the comment after reading this:

> Since I think this is the single thing that keeps me from moving from other .csx "runners".

@SlowLogicBoy in what "other .csx runner" does this currently work?

**Comment by adamralph** [comment]
Ignore last question, I just saw:

> @adamralph, it does, I just need to #r "full path to dll" instead of nuget.

Sorry for the noise.

**Comment by seesharper** [comment]
@SlowLogicBoy Are we good here?

**Comment by adamralph** [comment]
If a transitive #r works in this way in CSI.exe then it shouldn't it also
work in dotnet-script?

**Comment by seesharper** [comment]
#r fillpathtoassembly works exactly the same

**Comment by adamralph** [comment]
I see. Then I don't understand this comment:

> Since I think this is the single thing that keeps me from moving from other .csx "runners".

**Comment by SlowLogicBoy** [comment]
> @SlowLogicBoy Are we good here?

I'm good for now, but it will get quite difficult for me in the long term, if I need to test/run script in some kind of subfolder.

I'm using [RoslynPad](https://github.com/aelij/RoslynPad). But also searching for other solutions that would be x-platform compatible.

**Comment by filipw** [comment]
I think this should stay open - let's repurpose this issue for investigating the possibility of having self contained resolvers, which is my personal dream.
I also think that it needs to be documented 📚 that `#r nuget` discovery at the moment works as it does (not traversing up).

**Comment by seesharper** [comment]
Self contained resolvers should be possible at least in theory :) We would probably need to do a separate `dotnet restore` for each `#r nuget` and `#load nuget` unless we find a clever way around. The "advantage" of doing it like we do today is that we only need a single `dotnet restore` to gather all dependencies.

**Comment by seesharper** [comment]
@filipw I'm creating a new issue to track this

**Comment by Alumniminium** [comment]
So if I read this thread correctly, I can't organize my universal/reusable scripts somewhere else unelss I hardcode a #r dll path instead of nuget? That's terrible.

_/home/username**/scripts/shell.csx**_
```
#!/usr/bin/env dotnet-script
#r "nuget: CliWrap, 3.3.0"

using CliWrap;
using CliWrap.Buffered;

public static class shell
{
    public static string run(string command)
    {
        var parts = command.Split(' ',StringSplitOptions.RemoveEmptyEntries);
        var cmd = Cli.Wrap(parts[0])
                     .WithArguments(parts[1..])
                     .WithValidation(CommandResultValidation.None)
                     .ExecuteBufferedAsync()
                     .GetAwaiter()
                     .GetResult();
        if(string.IsNullOrEmpty(cmd.StandardOutput))
            return cmd.StandardError;

        return cmd.StandardOutput;
    }
}
```


_/home/username/**.config/bspwm/bspwmrc.csx**_

```
#!/usr/bin/env dotnet-script

#load "/home/username/scripts/shell.csx"

shell.run("ls");
```

> /home/username/scripts/shell.csx(4,7): error CS0246: The type or namespace name 'CliWrap' could not be found (are you missing a using directive or an assembly reference?)
