### ISSUE TITLE
Assembly Binding?

### ISSUE THREAD

**Issue by SlowLogicBoy** [filipw/dotnet-script#198]
```csharp
#! "netcoreapp2.0"
#r "nuget:NuGet.Client,*"
#r "nuget:NuGet.Configuration,*"
//#r "nuget:Nuget.Common,*"

using System.Linq;
using NuGet;
using NuGet.Configuration;
using NuGet.Repositories;

var repo = new NuGetv3LocalRepository(SettingsUtility.GetGlobalPackagesFolder(Settings.LoadDefaultSettings(null)));
var packages = repo.FindPackagesById("NuGet.Client");
var pkg = packages.Last();
var nuspec = pkg.Nuspec;
```

I get: `System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Common, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'NuGet.Common, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.IO.FileNotFoundException: Could not load the specified file.`

I've tried specifying versions, etc. Can't figure out how to make this work :).

I don't know if it's an Assembly Binding issue or NuGet.Client has something nasty and it's looking for that dll in working directory.

P.S. this works in .csproj

**Comment by seesharper** [comment]
Thanks for reporting this. We currently do very little with regards to assembly redirects. Now we have a case for this. Will look into this

**Comment by SlowLogicBoy** [comment]
https://gist.github.com/SlowLogicBoy/56769cfd66803c0d2608688c8bd08859
Here is csproj, it doesn't have any assembly redirects :/

**Comment by seesharper** [comment]
@SlowLogicBoy We have confirmed this to be a bug and we will be providing a fix for this as soon as possible.

**Comment by SlowLogicBoy** [comment]
Will there be a release soon? or should I use CI build?
