### ISSUE TITLE
Missing core assembly references

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#204]
@filipw  We have a pretty serious issue here probably because we now don't add inherited assemblies anymore.

Consider the following script 

```
#! "netcoreapp2.0"
#r "nuget:NetStandard.Library, 2.0.1"

using System;
using System.Net;

Console.WriteLine(typeof(WebProxy));
```

The `WebProxy` class comes from the `System.Net.WebProxy.dll` and is part of NetCoreApp2.0. 

When executing the script in debug mode we get 

```
$ dotnet script -d helloworld.csx
Current runtime is 'win'.
Creating project file for *.csx files found in C:\scriptdemo using netcoreapp2.0 as the default framework.
Parsing C:\scriptdemo\helloworld.csx
Project file saved to C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\script.csproj
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetStandard.Library" Version="2.0.1" />
  </ItemGroup>
</Project>
2.1.2
Restoring C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\script.csproj using the dotnet cli.
  Restoring packages for C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\script.csproj...
  Generating MSBuild file C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\obj\script.csproj.nuget.g.props.
  Restore completed in 166,19 ms for C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\script.csproj.
Reading dependency context from C:\Users\bri\AppData\Local\Temp\scripts\C\scriptdemo\script.csproj
Resolved NuGet package folders: C:\Users\bri\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder
Adding reference to an inherited dependency => Microsoft.CodeAnalysis
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.CSharp.Scripting
Adding reference to an inherited dependency => Microsoft.CodeAnalysis.Scripting
C:\scriptdemo\helloworld.csx(7,26): error CS0246: The type or namespace name 'WebProxy' could not be found (are you missing a using directive or an assembly reference?)
```

We can also see from the log that we do not add any runtime assemblies from netcoreapp2.0 so I guess that is why we see this error.

> Note Compilation assemblies for OmniSharp are not affected. They resolve correctly 

We need to be able to get all these assemblies from the dependency context loaded from the csproj file and that means that we probably need to specify the runtime identifier when restoring 

So instead of 

```
dotnet restore script.csproj
```

we need to do 

```
dotnet restore script.csproj -r [runtimeidentifier]  -> e-g win10-x64
```

The `DependencyContext` class has a method called `GetRuntimeAssemblyNames(runtimeIdentifer)` that will return a complete list of runtime assembly names if and only if we restore using the runtime identifier.

We should not go back to pulling these assemblies from the host (inheritedassemblies), but we should fix this in the `RuntimeDependencyResolver` class and make sure that we return the "core" assemblies so that they can be added in the `ScriptCompiler` 

I'm looking into this now

**Comment by seesharper** [comment]
I'm on top of it. Work in progress....

**Comment by filipw** [comment]
maybe we should pull them using https://github.com/filipw/dotnet-script/issues/161?

```
var assemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES");
var assembliesPaths = assembliesString.Split(Path.PathSeparator);
```

**Comment by seesharper** [comment]
That does not bring in all the assemblies we need. For instance, in the example above we need `System.Net.WebProxy.dll` and that is not part of `TRUSTED_PLATFORM_ASSEMBLIES`.  I think the safest thing we can do is to pull it from the dependency context since that is the closest thing we can get to the dependency context of a standard netcoreapp.

**Comment by filipw** [comment]
it's there on my machine

<img width="1031" alt="screenshot 2017-12-07 17 43 26" src="https://user-images.githubusercontent.com/1710369/33726742-30c89978-db76-11e7-93fe-d74d110a2e76.png">

**Comment by seesharper** [comment]
Okay, maybe I missed it. Let me have a second look :)

**Comment by filipw** [comment]
it's there on a Mac too, resolves to `/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.0/System.Net.WebProxy.dll`

**Comment by seesharper** [comment]
My mistake. Got it. I'll try just adding these references in the `ScriptCompiler` class. Then we don't have to touch any of the `DependencyModel` projects 👍

**Comment by filipw** [comment]
Yeah this looks like a super charged version of inheriting assemblies 😄

**Comment by seesharper** [comment]
It looks like it. Just hope it does not get us into trouble when somebody references `NetStandard.Library, 1.6.1`. I will give it a go. We have tests that covers this

**Comment by seesharper** [comment]
Remember that we could still do 
```
#! "netcoreapp1.1"
#r "nuget:NetStandard.Library, 1.6.1"
```
or `NetStandard.Library, 1.6.1` could come in through another NuGet package

**Comment by seesharper** [comment]
Adding 181 assemblies from `TRUSTED_PLATFORM_ASSEMBLIES` is a pretty aggressive approach, but I'll see if all tests still passes  😃

**Comment by seesharper** [comment]
There is a risk that we bring back #181

**Comment by seesharper** [comment]
Yep, we broke #181 which was the reason we went away from the inherited assemblies in the first place

**Comment by seesharper** [comment]
`dotnet restore -r [runtimeIdentifier]` does the trick though

**Comment by filipw** [comment]
I think we could do the same in OmniSharp too, then we just say it's a .NET Core 2 runner and .NET Core 2 tooling and that's it.
That said, if the runtime specific solution works, even better

**Comment by filipw** [comment]
On the other hand, I always wanted a runner with a default set of assemblies pre-referenced though, I'm not sure having to specify standard library over and over is a great experience too 😄

**Comment by seesharper** [comment]
The thing is that we actually don't need to bring in `#r "NetStandard.Library, 2.0.0"` anymore if we restore using the runtime identifier. The netcoreapp2.0 assemblies is already part of the dependency context 

```
This what a `csproj` file looks like without any nuget packages. The dependency context "understands" the target framework and provides all runtime assemblies. So in that sense you get what you want :)

<Project Sdk="Microsoft.NET.Sdk">                                     
  <PropertyGroup>                                                     
    <OutputType>Exe</OutputType>                                      
    <TargetFramework>netcoreapp2.0</TargetFramework>                  
  </PropertyGroup>                                                                                                  
</Project>                                                            
```

**Comment by filipw** [comment]
ahh then I will shut up 😂

**Comment by seesharper** [comment]
😄  In fact we could remove this as well 
https://github.com/filipw/dotnet-script/blob/e3767d3b2d39a03d299686394a02f60170dd585e/src/Dotnet.Script.Core/Templates/helloworld.csx.template#L2

since we bring in all netcoreapp2.0 assemblies

**Comment by seesharper** [comment]
I'll wrap this up and create a PR 👍 Then we should consider a 0.16.1 service release

**Comment by seesharper** [comment]
> then we just say it's a .NET Core 2 runner and .NET Core 2 tooling and that's it.

What I meant here that we need to be backward compatible. When NetCore 3.0 comes, we should still be able to execute scripts that "targets" NetCoreApp2.0. 😄
