### ISSUE TITLE
support custom filename in init

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#218]
`dotnet script init` creates `helloworld.csx`, it should be possible to pass in the filename instead.
Also, the default filename should be `main.csx`, as it's already been discussed that this file can have special importance in Nuget packages. Plus it would make sense as the "entry point".

**Comment by seesharper** [comment]
That would make perfect sense. In addition I think we should not create the default file if `dotnet  script init` is executed in a folder that already contains script files. I often run `dotnet script init` just to set up `launch.config` and `omnisharp.json` and then immediately delete the `helloworld.csx` file. :)

**Comment by seesharper** [comment]
@filipw FYI, I am working on it :)

**Comment by seesharper** [comment]
Fixed by #219
