### ISSUE TITLE
Setting NuGet package source inline? 

### ISSUE THREAD

**Issue by andmos** [filipw/dotnet-script#225]
Say I want to pick a different source for the NuGet package I'm using in my script, wouldn't it make sense to do that inline in the script, to keep it as self contained as possible? 
I'm thinkig something in the lines of 
```
#r "nuget: AutoMapper, 9.1.0, https://my-awesome-nuget-feed/nuget/"
```
where the last bit is an optional overload. 
I found #157 that brings on support for using a custom `nuget.config` file, but as mentioned having the feed as an optional inline overload would make the whole thing more explicit and self-contained. 

I guess you guys might have discussed this, so feel free to shut this issue down if you don't agree 👍 

EDIT: Thinking about it, doing something like that might come in conflict with what's done in Roslyn?

**Comment by filipw** [comment]
I'd like this stay compatible with what is planned for Roslyn. Note that custom sources may need other things such as credentials, so the syntax might grow even more complicated. 

Maybe a better solution would be to allow the feed info be passed as execution parameter instead?

**Comment by andmos** [comment]
>Maybe a better solution would be to allow the feed info be passed as execution parameter instead?

Yeah I can dig that. A lot of tools that reads config from files allows override at the CLI, so I think that would be a nice approch.

**Comment by filipw** [comment]
@andmos would it be OK to have a source as command line argument? `dotnet script foo.csx -sources https://my.source/`

**Comment by andmos** [comment]
Yeah would like that! Explicit and clear.

**Comment by filipw** [comment]
OK great, there is a way to do it with `.NET Core 2.1` 👍

**Comment by seesharper** [comment]
Fixed by #310

**Comment by andmos** [comment]
@seesharper can source be a local file on disk, like `--sources $(pwd)` ?

**Comment by seesharper** [comment]
It can be a local folder so that should work. Famous last words 😊

**Comment by andmos** [comment]
`$ dotnet-script src/TestScript/main.csx -s $(pwd)`
Worked like a charm 👍 
Great work guys!
