### ISSUE TITLE
Investigate scripts as global tools in .Net Core 2.1

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#228]
It would be nice if we could package a script as a global tool.
An example of such a package 

https://www.nuget.org/packages/dotnetsay/

```
<?xml version="1.0" encoding="utf-8"?>
<DotNetCliTool>
  <Commands>
    <Command Name="dotnetsay" EntryPoint="dotnetsay.dll" Runner="dotnet" />
  </Commands>
</DotNetCliTool>
```

Might be as simple as 

```
<?xml version="1.0" encoding="utf-8"?>
<DotNetCliTool>
  <Commands>
    <Command Name="dotnetsay" EntryPoint="main.csx" Runner="dotnet script" />
  </Commands>
</DotNetCliTool>
```

If not we can wrap the script execution inside a console app which seems to be recommended way of creating global tools. 

https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-net-core-2-1-preview-1/

**Comment by filipw** [comment]
done
