### ISSUE TITLE
Question: Is there a way to force to get latest version of nuget?

### ISSUE THREAD

**Issue by stefandevo** [filipw/dotnet-script#259]
Hi
Is there an option in the `#load "nuget:package.name, 1.0.0"` notation to force to get the latest version. It seems as if I put `*` as the version, it always takes the 'first' version. For example, I have a `1.0.0` and a `1.0.1`. When I run it will always take `1.0.0` if I specify `*` as version.

**Comment by seesharper** [comment]
Hi @stefandevo 
We actually don't process the version number in any way. 
If you execute your script with the debug option `-d`, you should be able to see the generated csproj file containing the package reference.

I did a quick test with Newtonsoft.Json and it produces the following package reference.

```
<PackageReference Include="Newtonsoft.Json" Version="*" />
```

This gave me the latest version of ´Newtonsoft.Json´

From the debug log 

```
Resolved runtime library Newtonsoft.Json located at C:\Users\bri\.nuget\packages\newtonsoft.json/11.0.2\lib/netstandard2.0/Newtonsoft.Json.dll
```
More information about floating versions here

https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions

**Comment by seesharper** [comment]
@stefandevo Are you still having this issue?

**Comment by stefandevo** [comment]
I will follow up on this one and create a test case the coming days.
What I had was, I created a new package 1.0, used that in the script, next, I created an update on the package 1.1, and ran the same script again. Then it just used the 1.0 package all the time. I will try to replicate that scenario.

**Comment by seesharper** [comment]
Any updates on this, @stefandevo ?

**Comment by seesharper** [comment]
The output shows multiple package references. Are you sure that you don't have more than one script in your folder or in any subfolder?

**Comment by stefandevo** [comment]
I do have multiple script in the same folder. Is this the issue?

**Comment by seesharper** [comment]
That is probably what is causing the error. It should however not be an issue as long as your are on >=0.23.0. 

See https://github.com/filipw/dotnet-script/pull/267 for more information

**Comment by stefandevo** [comment]
Executing that will get me into the REPL mode.

**Comment by seesharper** [comment]
What about `dotnet script -v` ?

**Comment by stefandevo** [comment]
better :-)
0.20.0

that explains the version issue. I did execute before I started testing:

curl -s https://raw.githubusercontent.com/filipw/dotnet-script/master/install/install.sh | bash

**Comment by stefandevo** [comment]
I executed it again with `sudo` and now I have 0.24

**Comment by stefandevo** [comment]
Before that, I moved my script around to another location, and then it worked; deleting other scripts in the same folder, did not fixed it, I have to use another folder.

**Comment by stefandevo** [comment]
So now the info also worked:

test dotnet script --info
Version             : 0.24.0
Install location    : /usr/local/lib/dotnet-script
Target framework    : netcoreapp2.0
Platform identifier : osx
Runtime identifier  : osx-x64

**Comment by seesharper** [comment]
Cool, and the Nuget package issue is resolved?

**Comment by seesharper** [comment]
@stefandevo Can you confirm that it works as expected with 0.24.0 ?

**Comment by stefandevo** [comment]
Yes
