### ISSUE TITLE
Extract Dotnet.Script.Runner package

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#26]
I'd split the CLI package and the runner package.

The runner package could be useful to anyone who wants to go from `project.json` => executable script easily, and support debugging scenarios too, which is a fair amount.

**Comment by atifaziz** [comment]
In that case, don't you think you have [some issues & problems](https://github.com/filipw/dotnet-script/blob/6a855f537568c0eef4c7c621f89fddd1260b5d1c/README.md#issues-and-problems) to deal with before going public with a runner package. :wink:
