### ISSUE TITLE
Add dotnet-script --info

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#263]
Something like 

```
dotnet script --info
```

yields some environmental information 

```
InstallLocation:     
TargetFramework:
Nuget Folders: (where we look for NuGet packages)
Commit hash: 
```

Users can install into different locations depending upon how we install 

* Install.sh
* Chocolatey
* Global tool  

When issues come in the information provided by `dotnet script --info` can be very valuable

**Comment by filipw** [comment]
Fixed by #282
