### ISSUE TITLE
Terminating the script runner (interactive)

### ISSUE THREAD

**Issue by tomgron** [filipw/dotnet-script#286]
With ctrl+c I can't get out of the process if I type something like "dotnet script"

**Comment by seesharper** [comment]
Hi @tomgron 

Could you execute `dotnet --info` and `dotnet script --version` and dump the output here?

**Comment by tomgron** [comment]
Windows PowerShell                                                                     
Copyright (C) Microsoft Corporation. All rights reserved.                              
                                                                                       
Loading personal and system profiles took 3102ms.                                      
 ⚡ TommiGrönlund@TOMMI-SURFPRO4  ~  dotnet script --info                             
Version             : 0.24.0                                                           
Install location    : C:\ProgramData\chocolatey\lib\dotnet.script\Dotnet.Script        
Target framework    : netcoreapp2.0                                                    
Platform identifier : win                                                              
Runtime identifier  : win10-x64                                                        
 ⚡ TommiGrönlund@TOMMI-SURFPRO4  ~  dotnet script --version                          
                                                                                       
0.24.0                                                                                 
 ⚡ TommiGrönlund@TOMMI-SURFPRO4  ~  $PSVersionTable                                  
                                                                                       
Name                           Value                                                   
----                           -----                                                   
PSVersion                      5.1.16299.251                                           
PSEdition                      Desktop                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                 
BuildVersion                   10.0.16299.251                                          
CLRVersion                     4.0.30319.42000                                         
WSManStackVersion              3.0                                                     
PSRemotingProtocolVersion      2.3                                                     
SerializationVersion           1.1.0.1                                                 
                                                                                       
                                                                                       
 ⚡ TommiGrönlund@TOMMI-SURFPRO4  ~  dotnet --version                                 
2.1.300-preview2-008530                                                                
 ⚡ TommiGrönlund@TOMMI-SURFPRO4  ~ 

**Comment by seesharper** [comment]
So it's from a PowerShell session. 

Could you describe the exact steps to reproduce ?

**Comment by tomgron** [comment]
Just started cmder (as Admin) and on Powershell session started the dotnet script - with no parameters. This seemed to create some kind of interactive session (some kind of prompt appeared) and once I hit CTRL-C, the app asks me "Do you want to terminate batch (Y/N)" and if I type Y and enter, the app never exits.

**Comment by seesharper** [comment]
Okay, I am not familiar with `cmder`. Could you try from a standard powershell session?

**Comment by tomgron** [comment]
That seems to work, apparently that has to do something with cmder - similar functionality works on node.exe though for some reason.

**Comment by filipw** [comment]
you can always quit the REPL session using `#exit` command too
