### ISSUE TITLE
Debugging Helloworld from VS Code does not work

### ISSUE THREAD

**Issue by Sankra** [filipw/dotnet-script#292]
```
System:
macOS 10.13.4
```

```
dotnet --version : 
2.1.300-rc1-008673
```

```
dotnetscript version:
Package Id         Version      Commands     
---------------------------------------------
dotnet-script      0.24.0       dotnet-script
```

## Steps to reproduce:
1. Install dotnet core 2.1 RC1
2. Install _dotnet-script_ as a global tool
3. Create empty folder and run `dotnet-script init`
4. Try running `Debug: Start Debugging`
5. Fails with:

![screen shot 2018-05-10 at 07 51 22](https://user-images.githubusercontent.com/634968/39855100-d4961120-542a-11e8-93b5-f1be231fe75d.png)

**Comment by filipw** [comment]
You can probably fix it by replacing 

```
            "program": "dotnet"
```

with 

```
            "program": "/usr/local/share/dotnet/dotnet"
```

Will need to check what happened. Which version of VS Code are you on?

**Comment by Sankra** [comment]
I'm on VS Code 1.23.0 and it worked when changing to `/usr/local/share/dotnet/dotnet`. 

I'll try to reinstall Code 😄

**Comment by filipw** [comment]
I have actually seen this in the past, and it was related to a corrupt update of VS Code. 1.23.0 came out just a week ago, so it could be the case here too.

VS Code actually reports that an instance is corrupt with a little notification, but it quickly goes away and it might not show up again (like described here https://github.com/Microsoft/vscode/issues/42282#issue-292241429).

**Comment by Sankra** [comment]
With a reinstalled VS Code and correct version of dotnet script in the path, everything is working again. Thanks for the help 👍
