### ISSUE TITLE
Possible to execute selected code in VSCode ?

### ISSUE THREAD

**Issue by toxonaut** [filipw/dotnet-script#301]
I would like to execute selected code in the VSCode (not the whole script). Is this possible ?

**Comment by filipw** [comment]
No, you'd need a dedicated VS Code Extension for that - dotnet-script is just a command line tool at the moment.
Functionally it supports everything that is needed though - you could pass a snippet of code to dotnet-script for execution the following way:

```
dotnet script eval Console.WriteLine(\"Hi\");
```

This is based on the `node -e console.log(\"foo\")` functionality. 
However a VS Code Extension is still needed to pick up i.e. your current selection and pass it to `dotnet-script`. We have started kicking tyres around a dotnet-script specific extension for VS Code specificially for scenarios like you ask for, the repo is here https://github.com/seesharper/dotnet-script-vscode so I'd recommend moving the issue there 🙂

**Comment by seesharper** [comment]
Tracking this here  https://github.com/seesharper/dotnet-script-vscode/issues/4
