### ISSUE TITLE
Can this run in .Net Core 2.0 instead of using the CLI?

### ISSUE THREAD

**Issue by Treemendus** [filipw/dotnet-script#302]
Is there anyway to run and execute a dynamic script using C# code in a .netcore 2.0 environment, instead of using the CLI?

**Comment by seesharper** [comment]
If you are looking into integrating `dotnet-script` into another application, you should be able to do that just by pulling in the `Dotnet.Script.Core` package. The `Dotnet.Script` console app is basically just an app that handles command line arguments and calls into `Dotnet.Script.Core`. 

Does that answer your question?

**Comment by Treemendus** [comment]
Yes it does thank you.
