### ISSUE TITLE
dotnet core sdk 2.1.300 not support

### ISSUE THREAD

**Issue by ahdung** [filipw/dotnet-script#303]
![default](https://user-images.githubusercontent.com/12094247/40788163-f9f943c6-6521-11e8-8aa9-587de0061a72.PNG)

**Comment by ahdung** [comment]
it's newer than 2.1.300 preview2

**Comment by seesharper** [comment]
Thanks for reporting this. We are looking into it

**Comment by filipw** [comment]
please update to 0.25.0, it should be fine - `dotnet tool update dotnet-script -g`

**Comment by ahdung** [comment]
@filipw still has problem:
The error means "Can't find out 'dotnet-script' command's executable file"
![_20180601104046](https://user-images.githubusercontent.com/12094247/40818131-4667327a-6588-11e8-9eaf-97d19c1494bb.png)

**Comment by filipw** [comment]
this looks like an issue with dotnet SDK itself, maybe it didn't generate the launch `exe` correctly. 

try going to `C:\Users\{user}\.dotnet\tools` and delete `dotnet-script.exe` and `dotnet-script.startupconfig.json` from there, and then to `C:\Users\{user}\.dotnet\tools\.store` and delete `dotnet-script` folder.

Then run fresh install again using `dotnet tool install dotnet-script -g`, this should hopefully fix it.

**Comment by ahdung** [comment]
@filipw I tried above steps except delete xxx.json, because this file is not exists, even I find it use a tool called "everything", actually, these steps same with "dotnet tool uninstall -g dotnet-script", and the problem still exists. I agree it's maybe a issue of dotnet SDK, I'll try go to their repository post issue. Thank you.

**Comment by filipw** [comment]
does it work with other tools? could you try i.e. `dotnet tool install dotnet-serve -g`? and then run `dotnet serve`.
I'd expect that to fail in your case too then

**Comment by ahdung** [comment]
@filipw same issue

**Comment by filipw** [comment]
yeah then definitely something is wrong with the .NET SDK here. could be (just wild guess) an issue with localization? 
I saw you opened an issue here https://github.com/dotnet/cli/issues/9396 - thanks 👍
Will follow this too, I'm also interested in understanding what is going on here

**Comment by ahdung** [comment]
@filipw Thank you for add issue reference. I hope it's a generic problem, not only me : (

**Comment by ahdung** [comment]
@filipw That issue is solved, I think the reason is `Envionment variables` too much. Anyway, use your tool already help me run the csx, Great, Thanks for your creation.

**Comment by filipw** [comment]
great 👍
