### ISSUE TITLE
[Q]Unified launch.json args for debugging scripts on different machines?

### ISSUE THREAD

**Issue by SlowLogicBoy** [filipw/dotnet-script#308]
I have git repo for my scripts, and it's difficult to go from one machine to another and debug script without changing `launch.json`. I was able to work around that when switching between my Linux and Windows machines, by using:
```json
"windows": {
                "args": [...]
            },
"linux":{
             "args":[...]
}
```

However migrating from one machine to another with same platform is quite difficult.
Is there a way to unify path to `dotnet-script.dll`?

Difficult parts:
"C:/Users/**{Username}**/.dotnet/tools/.store/dotnet-script/**0.25.0**/dotnet-script/**0.25.0**/tools/**netcoreapp2.1**/any/dotnet-script.dll"

**Comment by filipw** [comment]
Running `dotnet script init` on an already existing script fixes the path to `dotnet-script.dll`

```
~/Documents/dev/demos/2018-switzerland-netday-demos/releasenotes-generator$ dotnet script init
Creating VS Code launch configuration file
...'/Users/filip/Documents/dev/demos/2018-switzerland-netday-demos/releasenotes-generator/.vscode/launch.json' already exists' [Skipping]
...Fixed path to dotnet-script: '/Users/filip/.dotnet/tools/.store/dotnet-script/0.25.0/dotnet-script/0.25.0/tools/netcoreapp2.1/any/dotnet-script.dll' [Updated]
Creating OmniSharp configuration file
...'/Users/filip/Documents/dev/demos/2018-switzerland-netday-demos/releasenotes-generator/omnisharp.json already exists' [Skipping]
Creating default script file 'main.csx'
...Folder already contains one or more script files [Skipping]
```

Looks like there is a bug where it swallows a comma 😊atm but I think this is what you want, no?

**Comment by SlowLogicBoy** [comment]
Nice one, I guess that will work. 
Thanks.

The only problem I see now is I could commit my Username by mistake ^^. But I will solve that using git tricks I guess.

**Comment by RicardoNiepel** [comment]
You can use

> "**${env:USERPROFILE}**/.dotnet/tools/.store/dotnet-script/0.26.1/dotnet-script/0.26.1/tools/netcoreapp2.1/any/dotnet-script.dll"

It would be great if `Scaffolder.cs/CreateLaunchConfiguration` can also use **${env:USERPROFILE}** to prevent checking in usernames

**Comment by filipw** [comment]
that would make sense, yes

**Comment by seesharper** [comment]
We could do this as part of the Choco install and the install scripts (sh/ps1), but I have no idea how to set an environment variable as part of installing a global tool. 
Maybe we can ask @natemcmaster if this is even possible with global tools?

**Comment by natemcmaster** [comment]
Have you tried attaching the debugger to `dotnet-script.exe` instead of running `dotnet exec dotnet-script.dll`? I just tried it on Windows and it should work.

For example:
```
dotnet tool install --tool-path my-tools dotnet-script
```
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "program": "my-tools/dotnet-script.exe",
            "args": [
                "helloworld.csx"
            ],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```
If you use `dotnet tool install --global`, then the path dotnet-script.exe is in %USERPROFILE%/.dotnet/tools.

**Comment by lshearer** [comment]
Thanks, @natemcmaster! That worked well for me. 

For others' reference, this launch config (minimally adapted from that generated by `dotnet script init`) worked for me on macOS with a global install of dotnet-script:
 
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Script Debug (Global Tool)",
      "type": "coreclr",
      "request": "launch",
      "program": "${env:HOME}/.dotnet/tools/dotnet-script",
      "args": ["${file}"],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": true,
    }
  ]
}
```
I assume you could support all platforms with 

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Script Debug (Global Tool)",
      "type": "coreclr",
      "request": "launch",
      "program": "${env:HOME}/.dotnet/tools/dotnet-script",
      "args": ["${file}"],
      "windows": {
        "program": "${env:USERPROFILE}/.dotnet/tools/dotnet-script.exe",
      },
      "cwd": "${workspaceFolder}",
      "stopAtEntry": true,
    }
  ]
}
```
but I haven't tested this against Windows/Linux.
