### ISSUE TITLE
C# script return value

### ISSUE THREAD

**Issue by sanjuroo** [filipw/dotnet-script#313]
Is it possible to return value(object) from C# script? Is there any script execution method in Dotnet.Script.Core that could do it?

**Comment by SlowLogicBoy** [comment]
https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script.Core/ScriptRunner.cs#L21

**Comment by filipw** [comment]
The convention in scripts is that if the last line of the script is WITHOUT a semicolon, the result of that expression can be captured as return value. for example a script like that:

```
void Square(int number) 
{
    return number*number;
}

Square(5)
```

would have a return value `25` which you can capture using the `Execute<int>` method.
The alternative would be to have a script put the value into your custom host object and read it from there.

**Comment by filipw** [comment]
> when i am editing scripts in VS code, omnisharp doesn't know about these properties. Is there any way to tell omnisharp its host object property?

this is open issue in OmniSharp - see https://github.com/OmniSharp/omnisharp-roslyn/issues/1171
It's on my TODO, it will come soon

**Comment by sanjuroo** [comment]
thank you for your assistance
