### ISSUE TITLE
Why GetHashCode() produce difference value on dotnet-script?

### ISSUE THREAD

**Issue by wk-j** [filipw/dotnet-script#317]
I run this script and I got difference output for each time

```csharp
var a = "Hello";
Console.WriteLine(a.GetHashCode());
```

```bash
❯❯❯ dotnet-script -c Release ./src/hash/H.csx
1517928881
❯❯❯ dotnet-script -c Release ./src/hash/H.csx
-657730957
❯❯❯ dotnet-script -c Release ./src/hash/H.csx
-273244994
❯❯❯ dotnet-script -c Release ./src/hash/H.csx
856409267
```

```bash
❯❯❯ dotnet-script --info
Version             : 0.25.0
Install location    : /Users/wk/.dotnet/tools/.store/dotnet-script/0.25.0/dotnet-script/0.25.0/tools/netcoreapp2.1/any
Target framework    : netcoreapp2.1
.NET Core version   : 2.1.0
Platform identifier : osx
Runtime identifier  : osx-x64
```

**Comment by seesharper** [comment]
There is no guarantee that you will get the same hash code between runs 😄 


> The GetHashCode method for an object must consistently return the same hash code as long as there is no modification to the object state that determines the return value of the object's Equals method. Note that this is true only for the current execution of an application, and that a different hash code can be returned if the application is run again.

https://msdn.microsoft.com/en-us/library/system.object.gethashcode.aspx

**Comment by wk-j** [comment]
Thanks
