### ISSUE TITLE
Improve the formatting of console output

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#326]
We should review the places where console output is used and:
 - improve the usage of colors - after playing with some command line tools, a small set of well applied colors - red, yellow, green and perhaps blue/magenta can do wonders for readability of the output
 - improve indentation of the output

To clarify - I do not mean the script output itself as that should be up to the script itself to format its output, but the debug output, the errors/warnings output, the non-run script commands, REPL, compilation/export and so on

**Comment by seesharper** [comment]
Closed by #328 and #330
