### ISSUE TITLE
Automatic latest version check when running --version / --info

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#327]
When running `dotnet script --info` / `dotnet script --version` we could automatically check NuGet for the latest version of `dotnet-script` and suggest an upgrade.

**Comment by seesharper** [comment]
Good idea. I like it 👍

**Comment by seesharper** [comment]
There are two ways to deal with this as I see it. Either we do a super simple approach where we just ask for the latest release from GitHub and provide instructions on how to update (install.sh/ps1, choco or NuGet global tool). 

The other more involved way is to query NuGet respecting local NuGet.Config files. The latter involves referencing a couple of NuGet client packages.

**Comment by seesharper** [comment]
Closed by #370
