### ISSUE TITLE
How to consume a tool package?

### ISSUE THREAD

**Issue by thomaslevesque** [filipw/dotnet-script#337]
In a script, I need to consume a tool package, i.e. a package that doesn't contain assemblies to be references, but executable tools to be invoked by the script. For instance [vswhere](https://github.com/Microsoft/vswhere), [GitVersion](https://github.com/GitTools/GitVersion), etc.

Does dotnet script provide a way to get the path where the package is installed?

**Comment by seesharper** [comment]
Hi @thomaslevesque .

There is nothing in `dotnet-script` that does this for you, but that does not mean it can't be easily implemented. Let's take the example with `vswhere`.

The following script (VsWhere.csx) installs `VsWhere` into a "disposable folder" and then executes the binary contained in the package. 

```
#load "nuget:Dotnet.Build, 0.3.9"
using static FileUtils;
using static NuGet;
using static Command;
public static string VsWhere(string arguments)
{
    using(var disposableFolder = new DisposableFolder())
    {
        Install("vswhere", disposableFolder.Path);
        var pathToVsWhere = FindFile(disposableFolder.Path,"vswhere.exe");
        return Capture(pathToVsWhere, arguments).EnsureSuccessfulExitCode().StandardOut;
    }    
}
```

> Note: Dotnet.Build is just a collection of utility scripts we use for build scripts and I used that script package here just for brevity. Feel free to copy what you need from that package. 

You can now load this script from your main script like this

```
#load "VsWhere.csx"
WriteLine(VsWhere("-property installationPath"));
```

This will spit out a lot of stuff to the console, but at the end you should see the installation path of Visual Studio. As mentioned before, feel free to dissect the script package and pick what you need.  The code there is pretty straight forward. 😄

**Comment by thomaslevesque** [comment]
Nice, thanks! This seems to be just what I need.
