### ISSUE TITLE
ScriptRunner.Execute performance?

### ISSUE THREAD

**Issue by mikoskinen** [filipw/dotnet-script#338]
Thanks for the interesting project! We're currently seeing some performance issues with dotnet script and I wonder if we're missing some obvious setting / configuration. Our test script is:

`return "hello world";`

And the problem is that it takes ScriptRunner.Execute little more than 1 second to execute this, even if we execute the same script multiple times using the same ScriptRunner instance. The performance doesn't change from first execution to second or third execution. It feels like we're missing some "cache" toggle.

This is how we are initializing things:

                var runtimeDependencyResolver = new RuntimeDependencyResolver(logFactory);
                var compiler = new ScriptCompiler(logFactory, runtimeDependencyResolver);
                var runner = new ScriptRunner(compiler, logFactory, ScriptConsole.Default);

                var sourceText = SourceText.From(code);
                var context = new ScriptContext(sourceText, currentWorkingDirectory ?? Directory.GetCurrentDirectory(), args, null, OptimizationLevel.Release, ScriptMode.Eval, packageSources: packageSources);

                runner.Execute<string>(context);

Any ideas how we could make things faster? It's OK if ScriptRunner.Execute takes second or so for the first time but we would like things to be much quicker when we run the same script the second time.

**Comment by tomlm** [comment]
see PR #339 , this should give some improvements.

**Comment by tomlm** [comment]
This PR was accepted, the essence is that the DLLs produced by executing a script are automatically cached if the source script has not changed.

**Comment by seesharper** [comment]
Closed by #383
