### ISSUE TITLE
Fix package casing to use lower-case-with-dashes convention

### ISSUE THREAD

**Issue by adamralph** [filipw/dotnet-script#34]
![image](https://cloud.githubusercontent.com/assets/677704/20000994/699707fc-a27a-11e6-8155-dd2cf226dff1.png)

**Comment by filipw** [comment]
I don't think that's an established convention. For example `dotnet watch` is called `Microsoft.DotNet.Watcher.Tools` and `dotnet ef` is called `Microsoft.EntityFrameworkCore.Tools`.

The only convention mandatory is in the tool name (not package name) and that's already [dotnet-script](https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script/project.json#L21) indeed.

**Comment by filipw** [comment]
I suspect the reason why you are seeing this in some packages is that the package authors might have not known about `buildOptions > outputName`. Also, when you use `outputName` debugging of your tool doesn't work so there is that too.

**Comment by adamralph** [comment]
OK. Do you know why these things are sitting in .tools? I don't know where the other two came from.

**Comment by filipw** [comment]
The packages referenced as [tools](https://github.com/filipw/dotnet-script#usage) in `project.json` (not regular dependencies) show up there. on 10.10 you must have done a restore on a project that referenced the other ones.

**Comment by adamralph** [comment]
bizarre... they're still NuGet packages. Why put them in a special subfolder?

**Comment by filipw** [comment]
dont know, maybe so that they are easier to discover by the `dotnet.exe` driver?

**Comment by adamralph** [comment]
ah yes, perhaps it's a performance optimisation.
