### ISSUE TITLE
Feature request: Press UP in REPL to repeat previous command

### ISSUE THREAD

**Issue by geirsagberg** [filipw/dotnet-script#375]
It is a pretty common feature to be able to press the Up arrow to repeat the previous command. For example, both node and fsi have this.

Would be pretty nice to have this in the `dotnet script` REPL as well :)

**Comment by geirsagberg** [comment]
More specifically, to use the up and down arrows to navigate in command history within the REPL.

**Comment by filipw** [comment]
This was released today in 0.28.0 https://github.com/filipw/dotnet-script/releases/tag/0.28.0
