### ISSUE TITLE
Running published content gives error

### ISSUE THREAD

**Issue by amitkumarmahajan** [filipw/dotnet-script#377]
Hi,

I am getting error while running published content.
These are the steps I have done on cli -

1. dotnet script init
2. dotnet script publish main.csx --dll
3. This created publish folder with main.dll and obj folder
4.  Tried to run script as per documentation -
    dotnet publish\main.dll

**But above gives output if run command as -
      dotnet script exec publish\main.dll**

**Error -**

> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\abc\publish\'.
> Failed to run as a self-contained app. If this should be a framework-dependent app, add the D:\abc\publish\main.runtimeconfig.json file specifying the appropriate framework.

**Below are details if required -**
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by filipw** [comment]
> 4\. Tried to run script as per documentation -
>     dotnet publish\main.dll

you should not run using `dotnet publish\main.dll` but rather using `dotnet script exec publish\main.dll`.
if you don't want to be coupled to `dotnet script` for execution, you can also publish as executable, see more details here https://github.com/filipw/dotnet-script/releases/tag/0.26.0

hope this helps

**Comment by filipw** [comment]
ah didn't realize this - thanks for finding, corrected now 📚
