### ISSUE TITLE
How to add local reference

### ISSUE THREAD

**Issue by garfelddd** [filipw/dotnet-script#378]
I use visual studio 2017, and have problem to add local reference
I tried to add
```
#r "MyProject.Core"
using MyProject.Core;
```

And executed 'dotnet script run.csx' command but unfortunately compilator says about **CS0246** error what means that MyProject.Core cannot be found
Moreover i don't have intellisense in vs 2017 for dotnet script
Importing nuget packages also doesn't work but i'm more interested local refs now

**Comment by seesharper** [comment]
Hi @garfelddd 
Project references is not supported in C# scripting. You can however reference your compiled dll.

```
#r "[PathToDll]MyProject.Core.dll"
```

If you would like to reference NuGet packages and still have intellisense, you need to use VS Code with the C# extension. Language services are provided by the OmmiSharp project and comes bundles with the C# extension. In addition to referencing NuGet packages, you can also debug the script(s).

Hope that answers your question

**Comment by garfelddd** [comment]
Sweet. Thank you:)

**Comment by seesharper** [comment]
No problem 👍🙂

**Comment by TarasKuz** [comment]
Hi. Thank you for the great job!

Is it possible to reference another script file?
ex.:
- main.csx
- types.csx

**Comment by stephenllai** [comment]
> Hi. Thank you for the great job!
> 
> Is it possible to reference another script file? ex.:
> 
>     * main.csx
> 
>     * types.csx
> 
> 
> //main.csx #r "types.csx"

How about using #load?

**Comment by filipw** [comment]
yeah #load is for script references and #r is for assembly/nuget references

**Comment by sbansal-mdsol** [comment]
How to add a relative dll path to a dotnet-script? Is there an example to refer?
