### ISSUE TITLE
NuGet Imports do not allow specifying version ranges

### ISSUE THREAD

**Issue by robertmclaws** [filipw/dotnet-script#380]
The Roslyn script engine is an amazing platform, and its ability to import script files from NuGet packages is really cool. The problem becomes when you want to ship scripts that rely on NuGet packages. Because of versioning and incompatibility issues, a user is going to want to specify NuGet version ranges the _same way they do when constructing their NuGet packages_ in the first place. However, this does not work: the reference requires a single version specification; it breaks if you add a range or remove the version entirely.

This is a pretty severe limitation for script package developers.

**Version Used**: 
VS 15.9.0 Preview 4

**Steps to Reproduce**:

1. Create a new CSX file.
2. Add the following line to the top of the file:
```
#r "nuget: TypeLitePlus.Core, [2.0.1-CI-20181028-060241, 3.0)"
```
3. Run the script.

**Expected Behavior**:
I would expect that Roslyn would download the latest package available in the range.

**Actual Behavior**:
Roslyn throws the following error: 
```
Unable to restore packages from 'C:\Users\USERNAME\AppData\Local\Temp\scripts\D\Work\SomeApp\Branches\Dev\src\SomeApp.Web\clientapp\script.csproj'. Make sure that all script files contains valid NuGet references.
```

Moved from https://github.com/dotnet/roslyn/issues/30823

**Comment by seesharper** [comment]
Could you run the script with the - - debug option and paste the output here?

**Comment by filipw** [comment]
> Here's a sample of the script that uses a Package name but not a version.

As a workaround, you can use this syntax: `#r "nuget: TypeLitePlus.Core, *"`. 

When we first implemented this, there was no nuget concept of "empty" version, there was only a concept of "*". 
In .NET Core 2.1 it was extended to "empty", which we will have to incorporate too.

**Comment by robertmclaws** [comment]
Thanks @filipw! That will be a great short-term workaround. Hopefully it won't be too hard to implement the ranges to be able to deal with breaking changes longer-term.

**Comment by filipw** [comment]
this (both cases) is already fixed on the master branch by @atifaziz and will be supported in the next release
