### ISSUE TITLE
Allow NuGet references with no version number 

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#382]
Currently in master we do not match the following as a package reference

```
#r "nuget:AutoMapper"
```

**Comment by seesharper** [comment]
@atifaziz I think this actually used to work. Could it be that the new regex does not handle this? 😎

**Comment by atifaziz** [comment]
@seesharper I'd then we were missing tests for that :wink: because I didn't break any.

**Comment by seesharper** [comment]
My bad. It did not work before either :)
