### ISSUE TITLE
.Net Core 2.2

### ISSUE THREAD

**Issue by mhensen** [filipw/dotnet-script#403]
I am building a large microservice platform and to ease some of the deployments in kubernetes I want to offload some services in script variant. But my platform is all based on .Net Core 2.2

I tried to build dotnet-script with .Net Core 2.2 .. That all builds, but how do I install it in my dotnet tools?
I need the .Net Core 2.2 because my referenced dll's, used in the scripts, are Core 2.2 versions.. 

Right now I am not able to run dotnet script as the references are off. 
I need to build some scripts before I can do a implementation of my own host so I can test the reflection for finding the interfaces of the compiled scriptobject.

OmniSharp is picking up the referencesalright but running the script result in no error but also no output..  even a simple Console.WriteLine(1+1) results in nothing.. 

Hope somebody can help me out.. 

With kind regards,

Michael

**Comment by filipw** [comment]
At the moment dotnet-script doesn't support .NET Core 2.2. 

Things are unfortunately a bit complicated with that.
dotnet CLI doesn't allow multi-targeting for global tools, so we can't have one tool for both `netcoreapp2.1` and `netcoreapp2.2`, and we probably don't want to move to `netcoreapp2.2` yet as that would force all consumers to upgrade to `netcoreapp2.2` (especially as it is not LTS).

Nevertheless, normally it is possible to install both SDKs versions side by side, so in this case an SDK 2.2 for your own development and SDK 2.1 for script tooling. This should allow you to do everything script-wise except for loading `netcoreapp2.2` DLLs from scripts. However hopefully this can still be worked around - at the moment `netcoreapp2.2` doesn't offer a lot of advantages for libraries, so maybe you could simply retarget them to `netstandard2.0` and then they will become usable from scripts.

**Comment by filipw** [comment]
> Nevertheless, normally it is possible to install both SDKs versions side by side, so in this case an SDK 2.2 for your own development and SDK 2.1 for script tooling.

actually the current version of dotnet-script works if you *only* have SDK 2.2 installed too, you don't even need SDK 2.1.
So I guess the question just boils down if you are able to convert your `netcoreapp2.2` dependencies to `netstandard2.0`.

**Comment by mhensen** [comment]
Thanks for both swift answers!! 
@seesharper Yep.. I am targeting 2.2 as my whole framework is and my SDK dll is dependend on some of those dll's so that is 2.2 also.

@filipw Yep. I understand the problem.. I will try and see if I can target netstandards

Thanks for the answers!

**Comment by mhensen** [comment]
As @filipw pointed me to try to reference netstandards 2.0. I managaged to rearrange some dll's and made them .netstandards 2.0

Thanks again..
