### ISSUE TITLE
#!/usr/bin/env dotnet-script directive gives error "env: dotnet-script: No such file or directory"

### ISSUE THREAD

**Issue by lshearer** [filipw/dotnet-script#409]
I am unable to get the [recommended shebang directive](https://github.com/filipw/dotnet-script#running-scripts) to work. Instead, I get the error
```
env: dotnet-script: No such file or directory
```

`dotnet --info` results:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.1 [/usr/local/share/dotnet/sdk]
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
dotnet-script version 0.28.0

### Repro
1. Scaffold a fresh C# script using `dotnet script init`
2. `chmod +x main.csx`
3. `./main.csx`
4. Get `env: dotnet-script: No such file or directory`

Not sure if it's related, but while I get
```
$ which dotnet
/usr/local/share/dotnet/dotnet
$
```
I get nothing for dotnet-script
```
$ which dotnet-script
$
```

Now, if I change the directive from
```
#!/usr/bin/env dotnet-script
```
to
```
#!/usr/bin/env dotnet script
```
then it _does_ work.

But that's not the recommended or scaffolded shebang, and there should be nothing non-standard about my dotnet SDK or dotnet-script setups.

I would like to start proposing adoption of C# scripts to my team via dotnet-script, but having a consistent setup and usage will be important.

**Comment by seesharper** [comment]
Could you post the output from `dotnet script --info`

**Comment by lshearer** [comment]
```
$ dotnet script --info
Version             : 0.28.0
Install location    : /Users/lyleshearer/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any
Target framework    : netcoreapp2.1
.NET Core version   : 2.1.2
Platform identifier : osx
Runtime identifier  : osx-x64
```

**Comment by seesharper** [comment]
Okay, what happens if you do `dotnet-script --info` (with the hyphen) ?
If that fails, could you try to uninstall and then reinstall the dotnet script tool?

**Comment by lshearer** [comment]
Looks like the same results
```
$ dotnet-script --info
Version             : 0.28.0
Install location    : /Users/lyleshearer/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any
Target framework    : netcoreapp2.1
.NET Core version   : 2.1.2
Platform identifier : osx
Runtime identifier  : osx-x64
```

I should have noted that I can run both
```
dotnet script main.csx
```
and 
```
dotnet-script main.csx
```
successfully. It's just when calling `./main.csx` directly that I have any issues.

I've also tried uninstalling/reinstalling `dotnet-script` (via `dotnet tool`) before filing this ticket. I could try uninstalling/reinstalling the .NET SDK if that might help?

I don't understand how the `~/.dotnet/tools` segment ends up in my bash $PATH but yet `env` and `which` don't find it. Seems like that could be related, though? I'm not too familiar with how those utilities work, though.

**Comment by seesharper** [comment]
Try with another tool such as `dotnet-serve` . Does that behave the same way?

**Comment by seesharper** [comment]
Also could you list the contents of `/Users/lyleshearer/.dotnet/tools`

**Comment by lshearer** [comment]
```
$ ls ~/.dotnet/tools
dotnet-lambda   dotnet-script
```
And yeah, `which dotnet-lambda` and `/usr/bin/env dotnet-lambda` also fail.

Seems like more of an issue with .NET Global tools, then? I'll see if updating to the 2.2 SDK helps.

BTW, thanks for such quick responses! Much appreciated.

**Comment by seesharper** [comment]
No problem.👍 Let us know if that resolves your issue

**Comment by lshearer** [comment]
Updating the .NET Core SDK to 2.2 didn't help. Feels related to this issue with non-bash shells: https://github.com/dotnet/cli/issues/9321.

As a workaround, I've just added `~/.dotnet/tools` manually to my path in `~/.bash_profile`.

For anyone else having this problem, you can copy/paste this to do the same:
```
cat << EOF >> ~/.bash_profile
# Allow dotnet-script global tool to use shebang directive (https://github.com/filipw/dotnet-script/issues/409)
export PATH=\$PATH:~/.dotnet/tools
EOF
```

**Comment by filipw** [comment]
The reason why the shebang is generated for `dotnet-script` instead of `dotnet script` is because technically you could install the tool not as .net global tool but using `install.sh` that we have, and `dotnet-script` was supposed to cover both cases.

I guess we could detect if you have the .net global tool installed, and then we could generate the shebang in the init using `dotnet script` instead. I think going forward global tools are going to become the only installation mechanism anyway.

**Comment by lshearer** [comment]
I think either form makes sense to me as the recommended, given that `dotnet-script` _should_ be as discoverable as `dotnet`. But if `dotnet-script` is kept the default it might be worth noting something (and link to this issue?) [in the README](https://github.com/filipw/dotnet-script#running-scripts) until the issue is resolved in the dotnet cli (assuming it does, though comments [like this](https://github.com/dotnet/cli/issues/9321#issuecomment-393721213) seem hopeful).

**Comment by capyvara** [comment]
This is a dotnet-cli-tools bug.

It seems to add `~/.dotnet/tools` to the `$PATH` by using `/etc/paths.d/dotnet-cli-tools`

However tilde (~) expansion in `$PATH` is only supported by bash, the proper way is to setup the path at your `.bash_profile` file by adding:

`export PATH=$PATH:$HOME/.dotnet/tools`

Then `sudo rm /etc/paths.d/dotnet-cli-tools` since isn't needed anymore.

Related to: https://github.com/dotnet/cli/issues/9321

**Comment by seesharper** [comment]
Seems like we have confirmed this to be a dotnet-cli bug-
