### ISSUE TITLE
CompilationDependencyResolver is no longer compatible with OmniSharp

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#412]
I was updating OmniSharp to the new version of `CompilationDependencyResolver` (0.8.0 on Nuget, but the latest changes have not even been released yet, we are missing 0.9.0) and found out that it's not compatible with it anymore.

The bug is that when we call `CompilationDependencyResolver.GetDependencies()`, it ends up going through this line https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script.DependencyModel/Environment/ScriptEnvironment.cs#L32 which throws on non-.NET Core runtimes (and OmniSharp is not on it).

The workaround  in OmniSharp would be to call something like this `ScriptEnvironment.Default.OverrideTargetFramework(scriptOptions.DefaultTargetFramework);` before resolving dependencies but I would not like to put that in.

**Comment by seesharper** [comment]
Fixed by #458
