### ISSUE TITLE
Question: Is it possible to invoke and await async functions in a script?

### ISSUE THREAD

**Issue by TFTomSun** [filipw/dotnet-script#423]
Is it possible to invoke and await async functions in a script?

**Comment by filipw** [comment]
sure - do you have any specific issues?

Scripts use an implicit top level async context, meaning you can have loose awaits at the root of the script. For example:

```
var client = new HttpClient();
var response = await client.GetStringAsync("https://google.com");
```

You can also declare async global methods or use async methods inside classes (same as in full C#).

**Comment by TFTomSun** [comment]
thanks for the fast response. I was just confused by a problem, thats why i was not sure whether it has an async context. It works now ... thanks :)
