### ISSUE TITLE
way to browse object 

### ISSUE THREAD

**Issue by willhyper** [filipw/dotnet-script#427]
Hi I am new to dotnet script and all in for this powerful feature.
After searching internet, I don't have a solution to how to browse an object content.
For example, I can use ToUpper() because I know the object is string type.
What if I load a foreign object where I have no knowledge about what method, property, field, etc?
Is there a way that can list such information?

Thanks and appreciate to all inputs.

**Comment by willhyper** [comment]
ok....I gonna provide an answer to myself's question
one can do
`obj.GetType().GetProperties()`
or
`obj.GetType().GetMethods()`

**Comment by seesharper** [comment]
FYI, this is called reflection in C# and is not specific to C# scripting, 😀
