### ISSUE TITLE
version locking in config

### ISSUE THREAD

**Issue by mrtristan** [filipw/dotnet-script#441]
Any thoughts on a way to avoid the version locking that happens in using the `init`er? Example:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Script Debug",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "exec",
                "C:/Users/t/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any/dotnet-script.dll",
                "${file}"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```

Given a tree of folders of little `.csx` tools, updating `dotnet-script` will be a PITA given all of these explicit references to `0.28.0`. I tried a few things, some of them worked, but nothing that worked AND still had debugging working in vscode.

thoughts? Think there's any fanciness that can be done to make this reference dynamic, or any reason why you wouldn't want to?

**Comment by filipw** [comment]
We are looking at some ideas how to make it work. In the meantime, the workaround is to run `dotnet script init` again - it will automatically repair the path to the DLL in the `launch.json`.

**Comment by MartinJohns** [comment]
I just stumbled over this while taking a look at `dotnet-script`. A temporary workaround better than running `dotnet script init` would be to move the path to a user-specific variable, e.g. the VS Code configuration or an environment variable.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Script Debug",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "exec",
                "${config:dotnetScriptPath}",
                "${file}"
            ],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": true
        }
    ]
}
```

And in your `settings.json`:

```json
{
        "dotnetScriptPath": "C:/Users/UserName/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any/dotnet-script.dll"
}
```

**Comment by mrtristan** [comment]
@filipw running in to some problems so i took a crack at running `dotnet script init` and found that it actually "corrupted" the file.

after seeing the line: `...Fixed path to dotnet-script: 'C:/Users/t/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any/dotnet-script.dll' [Updated]` in the cli output, i noticed in the actual `launch.json` that it dropped the comma that was at the end, so for example, it wound up being:

```json
"args": [
    "exec",
    "C:/Users/t/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any/dotnet-script.dll"
    "${file}"
],
```

(note the missing comma on the second line)
