### ISSUE TITLE
Newtonsoft.Json Version problem.

### ISSUE THREAD

**Issue by SlowLogicBoy** [filipw/dotnet-script#443]
The problem is that if I reference nuget that references `Newtonsoft.Json` 12 it crashes since 11th version is already loaded (I assume `dotnet-script` references it), to use package like that I have to reference dll directly and load script through dotnet script interactive.
Similar problem: #129.

**code**:
```csharp
#r "nuget: Newtonsoft.Json, 12.0.1"
//#r "path\to\Newtonsoft.Json.dll"
using Newtonsoft.Json;

var obj = JsonConvert.DeserializeObject("{}");
Console.WriteLine(typeof(JsonConvert).Assembly.FullName);
Debugger.Break();
```

**command**:
```
dotnet script test.csx
```

Nuget:
```
Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
```

Dll:
```
Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

**dotnet script interactive:**

Nuget:
```
$ dotnet script
> #load "test.csx"
Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
>
```
Dll:
```
$ dotnet script
> #load "test.csx"
Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
>
```

**Environment:**
dotnet script version: 0.28.0
OS: Windows 10 x64
Omnisharp.json:
```json
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "netcoreapp2.1"
  }
}
```
dotnet-script path:
`C:/Users/User.Name/.dotnet/tools/.store/dotnet-script/0.28.0/dotnet-script/0.28.0/tools/netcoreapp2.1/any/dotnet-script.dll`

**Comment by filipw** [comment]
yep this is the same problem as mentioned in https://github.com/filipw/dotnet-script/pull/436.
The master branch already has the latest reference, it just hasn't been released yet.

**Comment by filipw** [comment]
The long term solution of course is to use AssemblyLoadContexts for this.

**Comment by seesharper** [comment]
This is now released 👍
