### ISSUE TITLE
"version": "*" doesn't resolve

### ISSUE THREAD

**Issue by perfectsquircle** [filipw/dotnet-script#45]
The instructions in  your README and on your [blog](http://www.strathweb.com/2016/10/introducing-c-script-runner-for-net-core-and-net-cli/) say to declare the dependency like so:

```json
"tools": {
    "Dotnet.Script": {
      "version": "*",
```

However there are only prerelease versions published on NuGet so far.

```
Dotnet.Script 0.7.0-beta
Dotnet.Script 0.6.0-beta
Dotnet.Script 0.5.0-beta
Dotnet.Script 0.4.0-beta
Dotnet.Script 0.3.1-beta
Dotnet.Script 0.3.0-beta
Dotnet.Script 0.2.0-beta
Dotnet.Script 0.1.1-beta
```

A `*` dependency doesn't resolve pre-release versions. This causes an error right off the bat when running `dotnet restore`.

```
error: Unable to resolve 'Dotnet.Script' for '.NETCoreApp,Version=v1.0'.
```

Maybe the instructions should indicate an exact version, a range [can cause problems later](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/managing-package-dependency-versions).

> Using the splat string could result in restoring packages from different builds, some of which may be further along than .NET Core 1.0.

**Comment by filipw** [comment]
Thanks, great point I totally missed it.
The reason why it's prerelease by the way, is not because I want it to be, but because the dependencies (Roslyn packages, Microsoft.DotNet.ProjectModel) are so I'm forced to use pre as well.

**Comment by filipw** [comment]
fixed with https://github.com/filipw/dotnet-script/commit/78b5a39a8128fd86a9dca596968fb031821ead5e
