### ISSUE TITLE
Passed config file is modified and becomes invalid

### ISSUE THREAD

**Issue by TFTomSun** [filipw/dotnet-script#463]
dotnet-script myscript --configfile PathToMzConfigFile

The nuget.config gets copied to the temporary project location. But for some reason it is modified, which is from my point of view not ok. For example nuget.org gets automatically added, which I don't want in an enterprise environment. 

Unfortunately even some important parts are completely removed. The whole packageSourceCredentials section gets removed, which makes dotnet-script fail, when accessing the repositories that require those credentials.

Is there any workaround to avoid that modification?

From my point of view the best solution would be if dotnet-script is executed in the context of the script file. Then the nuget logic to find the config in any folder above would also work, which doesn't currently. 
The other solution would be to find the nuget.config in the directories above when creating the temp project, and copy it ***unmodified*** into the temp script project folder.

**Comment by TFTomSun** [comment]
Here's one example:

Source Nuget.Config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value=".nuget/packages" />
    <add key="repositoryPath" value=".nuget/installed" />
  </config>

  <packageSources>
    <clear />

    <add key="local" value=".nuget/repository" />
     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="myget" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"></add>
    <add key="PrivateFeed" value="%Nuget_PrivateFeedAddress%" />
  </packageSources>
  <disabledPackageSources>
    <add key="local" value="true" />
    <add key="myget" value="true" />
    <add key="nuget.org" value="true" />
  </disabledPackageSources>

  <packageSourceCredentials>
    <PrivateFeed>
      <add key="Username" value="%Nuget_PrivateFeedUserName%" />
      <add key="ClearTextPassword" value="%Nuget_PrivateFeedApiKey%" />
    </PrivateFeed>
  </packageSourceCredentials>
  <apikeys>
     <add key="PrivateFeed" value="%Nuget_PrivateFeedEncryptedApiKey%" /> 
  </apikeys>
</configuration>
````
The unintended modified config in the dotnet script execution folder:

```xml

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  <add key="local" value="z:\Misc\_Thomas\scripts\.nuget/repository" />
  <add key="myget" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  <add key="PrivateFeed" value="... this environment variable gets resolved" />
</packageSources>
  <config>
    <add key="globalPackagesFolder" value="... this becomes a full path" />
    <add key="repositoryPath" value="...this becomes a full path too" />
  </config>
  <bindingRedirects>
    <add key="skip" value="False" /> <!-- this stuff is new and not wanted -->
  </bindingRedirects>
  <packageRestore>
    <add key="enabled" value="True" /><!-- this stuff is new and not wanted -->
    <add key="automatic" value="True" /><!-- this stuff is new and not wanted -->
  </packageRestore>
  <apikeys>
    <add key="... feed name gets resolved" value="..this environment variable gets resolved too" />
    <add key="PrivateFeed" value="...this gets resolved too" />
  </apikeys>
  <disabledPackageSources>
    <add key="local" value="true" />
    <add key="myget" value="true" />
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
</configuration>


```

**Comment by filipw** [comment]
yeah this is how it used to work - we'd simply copy the `Nuget.config` into the temp directory and use it there.
The behavior that you describe here as problematic to you, was introduced in this PR https://github.com/filipw/dotnet-script/pull/368 to solve a different problem, where copying the `Nuget.config` straight up wouldn't work.

if we included the other missing tags (packageSourceCredentials, clear) would it resolve this for you?

**Comment by TFTomSun** [comment]
@filipw well, if i change the environment variables it would still not affect the already copied nuget.config. And I don't want to have my credentials written down to that file. That might lead to unexpected exposure of credentials, when you publish it. 

Anyways, I feel that the solution of #368 is a dirty hack that will always lead to problems. I'm afraid that you can't cover all features of the nuget.config, when you start messing around with it.

As far as I understand #368 is about publishing. I don't fully understand the problem, but wouldn't it be sufficient to make that config resolution as an optional build parameter when you publish?

**Comment by TFTomSun** [comment]
@filipw and whats about my other suggestion. Why not creating the temp project at the script location? It took me a while to understand that there's a project created somewhere completely outside of the context of my script. I think it would be much more transparent if we could at least configure it to create the temp project where the script is located.
