### ISSUE TITLE
Line numbers in unhandled exception

### ISSUE THREAD

**Issue by nizmow** [filipw/dotnet-script#474]
It would be fantastically useful if the line number could be output with an exception message, so we could tell roughly where the exception occurred. I don't know what more to add other than that!

Thanks!

**Comment by seesharper** [comment]
@nizmow It should output the line number. Do you have an example where this does not work?

**Comment by nizmow** [comment]
Unable to replicate -- and I swear I had a sample last week, but now appears to work fine. Let that be a lesson to me to include code in any issue. Sorry, thanks for your time!

**Comment by seesharper** [comment]
No problem. 👌👍
