### ISSUE TITLE
Get a null object exception when including Process.Start in script

### ISSUE THREAD

**Issue by sls1j** [filipw/dotnet-script#481]
The script itself doesn't compile but prints out the following message

**Object reference not set to an instance of an object.**

Example script:

```
#! "netcoreapp2.1"

Process.Start("cmd.exe");
```
Running Version 0.30.0

**Comment by filipw** [comment]
it works on my machine 😀

can you please run `dotnet script {script file} --debug --no-cache` and post the output?

**Comment by sls1j** [comment]
It works on my machine now too :)  .The command you mentioned clear up the
issue.  Maybe something bad in a cache somewhere. Anyway here's the
output.  Thanks for the help!

PS C:\dev\glue\Scripts> dotnet.exe script test.csx --debug --no-cache
dbug: Dotnet.Script.Core.Commands.ExecuteScriptCommand[0]
      The script C:\dev\glue\Scripts\test.csx was executed with the
'--no-cache' flag. Skipping cache.
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Creating project file for C:\dev\glue\Scripts\test.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\dev\glue\Scripts\test.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to
C:\Users\bdickey\AppData\Local\Temp\scripts\C\dev\glue\Scripts\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp2.1</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup></ItemGroup>
      </Project>
dbug: Dotnet.Script.DependencyModel.Context.DotnetRestorer[0]
      Restoring
C:\Users\bdickey\AppData\Local\Temp\scripts\C\dev\glue\Scripts\script.csproj
using the dotnet cli. RuntimeIdentifier : win10-x64 NugetConfigFile:
C:\Users\bdickey\AppData\Roaming\NuGet\NuGet.Config
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Executing 'dotnet restore
"C:\Users\bdickey\AppData\Local\Temp\scripts\C\dev\glue\Scripts\script.csproj"
-r win10-x64  --configfile
"C:\Users\bdickey\AppData\Roaming\NuGet\NuGet.Config"'
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        Restore completed in 294.58 ms for
C:\Users\bdickey\AppData\Local\Temp\scripts\C\dev\glue\Scripts\script.csproj.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring
C:\Users\bdickey\AppData\Local\Temp\scripts\C\dev\glue\Scripts\script.csproj
took 1275ms
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Configuration/Optimization mode: Debug
Microsoft Windows [Version 10.0.17763.720]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\dev\glue\Scripts>
