### ISSUE TITLE
R2R, Single File and IL Link Trim support 

### ISSUE THREAD

**Issue by gdmka** [filipw/dotnet-script#490]
Hi, do you have a roadmap of supporting new features from .NetCore 3?

I assume ReadyToRun may benefit general platform dependent script startup while Single File + Trimmed with the distribution of  units of exection that do not depend on host .Net framework.

Given that, i cannot stress to ask if you plan to publish nuget packages that will not depend on .NETCoreApp 2.1 runtime?

**Comment by SlowLogicBoy** [comment]
Looks like Single File feature is already [here](https://github.com/filipw/dotnet-script/pull/496) (0.50.2, I got it from Build Artifacts)

Also +1 to Trimmed option (/p:PublishTrimmed=true)

**Comment by gdmka** [comment]
@SlowLogicBoy 
According to various sources (e.g. Scott Hanselman) there's an IL Linker flag `TrimmerRootAssembly` specifying the assmeblies, types, methods that not need to be trimmed.
Given that, a trimmed script is feasible although it would cede the burden of describing the untrimmed atrifacts on an end user. So it's tricky.

But the R2R  feature comes hand in hand with single file as i believe it should speed up the CLR stratup since and general scipt execution time because .Net Core isn't the platform for running C#/F# code as scripts.

@filipw can you elaborate please if Ready To Run is expected anytime?
