### ISSUE TITLE
CSX test runner

### ISSUE THREAD

**Issue by plaisted** [filipw/dotnet-script#494]
Is there a recommended approach to writing tests for CSX scripts? Both powershell (Pester) and golang (built in) have easy ways to run and report on tests for single files. It would be nice to have a way to have a script file `foo.csx`, write tests for it in `foo.test.csx` and be able to run `dotnet script test` to execute the *.test.csx files in the current directory. 

This is something that should be possible currently by just running the `foo.test.csx` file but that would require a ton of boilerplate code every time (eg. using XUnit AssemblyRunner). Is a streamlined approach to this something that has been considered or does something similar already exist?

**Comment by seesharper** [comment]
Hi @plaisted. I've created `ScriptUnit` just for this purpose. Check it out here. https://github.com/seesharper/ScriptUnit

**Comment by plaisted** [comment]
This looks like what I was looking for. Appreciate the work @seesharper
