### ISSUE TITLE
Cleaning the `Under the hood` project

### ISSUE THREAD

**Issue by mrtristan** [filipw/dotnet-script#497]
My goal with this issue is to i guess request a `clean` command and perhaps an update to the docs that points out how to get at the under the hood project file dir without going spelunking through source to find that

I'm trying to figure out what the problem is with this particular script that i'm working on (that i haven't opened in a while) and i'm getting errors. These errors aren't in my mind with this tool, but the tool seemingly is leaving me in a place where i can't move forward at all.

Example:
all i'm executing is 
`dotnet script .\main.csx`

Error I'm receiving in the cli:
`An item with the same key has already been added. Key: Microsoft.NETCore.App`

(for whatever it's worth, this error also shows in vscode's output)

This to me sounds like some project file garbage that likely has to do with the upgrade to 3.0. My initial desire here is to run a clean and perhaps get at the project file that's created under the hood and perhaps kill all of it.

as a shot in the dark, i did try running `dotnet script init`

Thoughts?
Thanks

**Comment by seesharper** [comment]
Hi @mrtristan 

Could you provide the script that you are trying to execute?

**Comment by seesharper** [comment]
You can also see the the detailed information if you execute `dotnet script main.csx --debug --no-cache`

**Comment by mrtristan** [comment]
for whatever it's worth, i just got it to work by replacing the entire contents of the script with nothing more than a `Console.WriteLine`, which worked, then i put everything in the script back and it worked. Does that make sense to you in that it could trigger some sort of dependency or project rebuild under the hood due to the nuget / ref changes?

(i can still share the script but it's nothing terribly interesting, just some api calls and saving json files.)

The only thing that's "interesting" in the script is that it references another `csx` by using `#load` which itself just uses

```c#
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.IO;
```

**Comment by mrtristan** [comment]
sorry for missing the `debug` command, i thought that was only relating to the packaging step with the way it's in the README.

may or may not be interesting: now that it's working, the output from running the script with or without `debug` does not change

**Comment by seesharper** [comment]
It makes sense since we have a cache that gets cleared if you change the script. It is however hard to tell what caused the error in your specific case, but I would guess that something got corrupted. If you are on *nix, you can clear all caches by executing `rm -rf $TMPDIR/scripts` 

> may or may not be interesting: now that it's working, the output from running the script with or without debug does not change

That's because the script is running from a compiled/cached dll so there is not all that much to log. Executing with `--no-cache -debug` should yield the details

**Comment by mrtristan** [comment]
sorry to pick on minutiae, but i did try running with `--nocache` and didn't have any success, is it `--no-cache` like you just mentioned or `--nocache`?

also, i'm on windows. know the directory off of the top of your head for where things live?

and regarding my first sentence in the issue, what are your thoughts on having some sort of `clean` command or should that essentially be made superfluous by `nocache`?

**Comment by seesharper** [comment]
`dotnet script -h` should print out all options. And yes, it is `--no-cache` 😀which also by the way clears the cache for that script

**Comment by mrtristan** [comment]
AH. i think that may be the core of the problem here. the readme mentions `nocache` where it seems to be `no-cache` per what i'm seeing in the code. that would explain why i couldn't get a clean build

(unless of course it's smart enough for that not to be an issue, however in my tests right now i'm seeing an output difference between the two...)

**Comment by mrtristan** [comment]
https://github.com/filipw/dotnet-script/pull/498

**Comment by seesharper** [comment]
Perfect. Approved. Merging when CI completes 👍Thanks

**Comment by mrtristan** [comment]
@seesharper FYI: i'm in a different script and getting this error again. I can fight my way past it but here's the stack in case it shines a light on anything:

content of `main.csx`:

```c#
#! "netcoreapp2.1"
#r "nuget: eG_CoreUtils.Vendor.REDACTED_Processors, 1.6.1000"

Console.WriteLine("xxx");

Debugger.Break();
```

output from running `dotnet script main.csx --debug`
```
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\REDACTED\dotnet-scripts\testground\main.csx
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Creating project file for C:\REDACTED\dotnet-scripts\testground\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\REDACTED\dotnet-scripts\testground\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp2.1</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup>
          <PackageReference Include="eG_CoreUtils.Vendor.REDACTED_Processors" Version="1.6.1000" />
        </ItemGroup>
        <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
          <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
        </Target>
      </Project>
dbug: Dotnet.Script.DependencyModel.Context.CachedRestorer[0]
      Skipping restore. C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj and C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj.cache are identical.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj took 11ms
System.ArgumentException: An item with the same key has already been added. Key: Microsoft.NETCore.App
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Dotnet.Script.Core.ScriptCompiler.CreateScriptOptions(ScriptContext context, IList`1 runtimeDependencies) in D:\a\1\s\src\Dotnet.Script.Core\ScriptCompiler.cs:line 83
   at Dotnet.Script.Core.ScriptCompiler.CreateCompilationContext[TReturn,THost](ScriptContext context) in D:\a\1\s\src\Dotnet.Script.Core\ScriptCompiler.cs:line 128
   at Dotnet.Script.Core.ScriptEmitter.Emit[TReturn,THost](ScriptContext context) in D:\a\1\s\src\Dotnet.Script.Core\ScriptEmitter.cs:line 23
   at Dotnet.Script.Core.ScriptPublisher.CreateScriptAssembly[TReturn,THost](ScriptContext context, String outputDirectory, String assemblyFileName) in D:\a\1\s\src\Dotnet.Script.Core\ScriptPublisher.cs:line 99
   at Dotnet.Script.Core.ScriptPublisher.CreateAssembly[TReturn,THost](ScriptContext context, LogFactory logFactory, String assemblyFileName) in D:\a\1\s\src\Dotnet.Script.Core\ScriptPublisher.cs:line 47
   at Dotnet.Script.Core.Commands.PublishCommand.Execute(PublishCommandOptions options) in D:\a\1\s\src\Dotnet.Script.Core\Commands\PublishCommand.cs:line 45
   at Dotnet.Script.Core.Commands.ExecuteScriptCommand.<GetLibrary>g__CreateLibrary|6_0(<>c__DisplayClass6_0& ) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteScriptCommand.cs:line 68
   at Dotnet.Script.Core.Commands.ExecuteScriptCommand.GetLibrary(ExecuteScriptCommandOptions executeOptions) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteScriptCommand.cs:line 62
   at Dotnet.Script.Core.Commands.ExecuteScriptCommand.Run[TReturn,THost](ExecuteScriptCommandOptions options) in D:\a\1\s\src\Dotnet.Script.Core\Commands\ExecuteScriptCommand.cs:line 34
   at Dotnet.Script.Program.<>c__DisplayClass4_0.<<Wain>b__9>d.MoveNext() in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at Dotnet.Script.Program.Wain(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 251
   at Dotnet.Script.Program.Main(String[] args) in C:\Users\VssAdministrator\AppData\Local\Temp\tmpCD12\Dotnet.Script\Program.cs:line 27
```

**Comment by mrtristan** [comment]
running with nocache solves it (even though the script was completely changed and cleared out to just the console write and debug line)

running `dotnet script main.csx --debug --no-cache`:

```
                                                                                                                                                dbug: Dotnet.Script.Core.Commands.ExecuteScriptCommand[0]
      The script C:\REDACTED\dotnet-scripts\testground\main.csx was executed with the '--no-cache' flag. Skipping cache.
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Creating project file for C:\REDACTED\dotnet-scripts\testground\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing C:\REDACTED\dotnet-scripts\testground\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp3.0</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup>
          <PackageReference Include="eG_CoreUtils.Vendor.REDACTEDProcessors" Version="1.6.1000" />
        </ItemGroup>
        <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
          <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
        </Target>
      </Project>
dbug: Dotnet.Script.DependencyModel.Context.DotnetRestorer[0]
      Restoring C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj using the dotnet cli. RuntimeIdentifier : win10-x64 NugetConfigFile: C:\REDACTED\dotnet-scripts\NuGet.Config
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Executing 'dotnet restore "C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj" -r win10-x64  --configfile "C:\REDACTED\dotnet-scripts\NuGet.Config"'
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        Restore completed in 16.42 sec for C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring C:\Users\t\AppData\Local\Temp\scripts\C\REDACTED\dotnet-scripts\testground\netcoreapp3.0\script.csproj took 17345ms
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Configuration/Optimization mode: Debug
xxx
```

**Comment by seesharper** [comment]
Could you try without `#! "netcoreapp2.1"` ?

**Comment by mrtristan** [comment]
too late, the `no-cache` fixed it so can't test further. i did try changing it to 3.0 before going at it with the `no-cache` and it yielded the same error. are those shebang lines even used on windows? excuse my ignorance there.

i'm sure i'll get another opportunity to test the theory at some point as i have a bunch of these scripts that will have cached project files, but fundamentally what do you think about this? should this project file targeting update be auto-magical or should it require developer intervention after an error as it is now?

**Comment by seesharper** [comment]
No, it should not require the developer to do anything. So that is a bug indeed. I'll have a look at the code and see where and why we end up here

**Comment by mrtristan** [comment]
found other script with the issue. commented out the shebang line and it yielded the same error `An item with the same key has already been added. Key: Microsoft.NETCore.App`

**Comment by andmos** [comment]
Just had this error myself, used a script with `#! "netcoreapp2.0"` that failed with `An item with the same key has already been added. Key: Microsoft.NETCore.App`. Removed the shebang solved the issue. In my case, I actually _need_ the caching, since I run the script out of a container and the startup-time without caching was significant. Commit: https://github.com/andmos/BikeshareClient/commit/66f6620f539870b95cdc9daa165c3bba88614d8e

**Comment by mrtristan** [comment]
@andmos i'm wondering if it was actually the shebang removal or if it was more of a "script changed so invalidate" kind of situation. the latter is more what i was experiencing per my recollection. to test the theory try and put it back and see what happens

**Comment by andmos** [comment]
Putting the shebang back results in the same error. Since I run the script as a part of a `docker build`, the environment is "clean" with no state or cache from before, the result will be invariable.
From the build _with shebang_:
```shell
Step 1/5 : FROM andmos/dotnet-script
 ---> 38ba44e9f481
Step 2/5 : WORKDIR /scripts/
 ---> Using cache
 ---> 05b90fa0789f
Step 3/5 : COPY main.csx main.csx
 ---> Using cache
 ---> b007647fefca
Step 4/5 : RUN ["dotnet", "script", "main.csx" , "dryrun"]
 ---> Running in ed42ee757867
An item with the same key has already been added. Key: Microsoft.NETCore.App
The command 'dotnet script main.csx dryrun' returned a non-zero code: 1
```

From the build _without_:

```shell
Step 1/5 : FROM andmos/dotnet-script
 ---> 38ba44e9f481
Step 2/5 : WORKDIR /scripts/
 ---> Running in 08e56dcd1b42
Removing intermediate container 08e56dcd1b42
 ---> 64424ddc193e
Step 3/5 : COPY main.csx main.csx
 ---> 30f0ac4d6432
Step 4/5 : RUN ["dotnet", "script", "main.csx" , "dryrun"]
 ---> Running in 76a9c7cb685e
Removing intermediate container 76a9c7cb685e
 ---> 63817e2e088e
Step 5/5 : ENTRYPOINT ["dotnet", "script", "main.csx"]
 ---> Running in 59f48c1616e5
Removing intermediate container 59f48c1616e5
 ---> be2fec735db7
Successfully built be2fec735db7
```

**Comment by mrtristan** [comment]
good info. ty

**Comment by seesharper** [comment]
That shebang is a leftover from way back when we had no other way of informing OmniSharp about the target framework for which to provide language services/intellisense. We now do this through `omnisharp.json` so this is really not needed any more.
