### ISSUE TITLE
Remote script text/html bug

### ISSUE THREAD

**Issue by sanjuroo** [filipw/dotnet-script#509]
Dotnet script return message: The media type 'text/html' is not supported when executing a script over http/https when executing remote script. For example raw url's from gitlab. When i execute these url's in browser they return text/plain, but i will get above message from dotnet script.

**Comment by seesharper** [comment]
Do you have something we can test against on GitLab?

**Comment by sanjuroo** [comment]
Sorry, nevermind, problem was with gitlab itself and it's bad documentation about public snippets that should run without authentication, but ofc not in a private project. So when running remote script login html response kicked in, thus text/html. Through browser it worked because i was logged in. Thanks for interest.
