### ISSUE TITLE
Resolving nuget packages in script package

### ISSUE THREAD

**Issue by sanjuroo** [filipw/dotnet-script#510]
I created nuget script package with main.csx. This script has dependency on some nuget package. When i consume it in other scripts: #load "nuget:my-script, 1.0.0" i have to specify same nuget dependencies in these scripts, otherwise i get error from main.csx about missing assembly reference. I expected from dotnet script that it will load nuget package scripts and resolve their dependencies. Or am i doing something wrong?

**Comment by seesharper** [comment]
@sanjuroo  You have to specify the dependencies in the `nuspec`file for your script package
