### ISSUE TITLE
Prevent 'dotnet script' to swallow its command line parameters

### ISSUE THREAD

**Issue by gsscoder** [filipw/dotnet-script#516]
Hi, first of all let me tell you how much I appreciate this project. The possibility to referencing **NuGet** packages and loading other scripts makes it a first class **.NET** development environment!

I discovered this (I would say _behaviour_, not a real issue) trying to use [verbs](https://github.com/commandlineparser/commandline/wiki/Verbs), a feature of a [cmd line](https://github.com/commandlineparser/commandline) project I've started years ago.

It's more easy to see this simple code instead of what I'm trying to do with the library:
```csharp
using System;
using System.Linq;
if (Args.Count() == 0)
{
    Console.WriteLine("nothing to do");
    Environment.Exit(1);
}
if (Args[0].Equals("init") || Args[0].Equals("exec"))
{
    Console.WriteLine("yeah");
}
```
A console output is better than a lot of words:
```sh
PS C:\Temp> dotnet script .\swallow.csx exec
Run a script from a DLL.

Usage:  exec [arguments] [options]

Arguments:
  dll               Path to DLL based script

Options:
  -d | --debug      Enables debug output.
  -? | -h | --help  Show help information
``` 

Is there a way to suppress this behaviour?

Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Thank you.

Regards,
Giacomo S. S.

**Comment by seesharper** [comment]
Hi @gsscoder and thanks for those kind words. Appreciate it.

If you pass the arguments like this `PS C:\Temp> dotnet script .\swallow.csx -- exec`, the args will be passed down to the script. Everything after the double hyphen is passed to the script as is and not interpreted by `dotnet-script`.

Alternatively you can create a self contained executable with `dotnet script publish swallow.csx`. That executable will "swallow" those args

**Comment by gsscoder** [comment]
Thank you, @seesharper! I completely forgot about `--`! I'll check also the second solution.

Kind words are deserved, this project is really cool.

Have nice day,
Giacomo
