### ISSUE TITLE
Allow a name to be passed when creating a self contained executable

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#517]
Today we currently don't support specifying a name `-n somename` when doing `dotnet script publish`. It also incorrectly default to the name `script` instead of defaulting to the name of the script file.

**Comment by JonLopezGarcia** [comment]
I've started to look at it and have already change the default name of the published exe by changing the name of the generated project file. Is it the way to go? Had you another implementation in mind for this feature?
