### ISSUE TITLE
dotnet core 3.1.2 compatibility (on linux)?

### ISSUE THREAD

**Issue by ghesketh** [filipw/dotnet-script#527]
**> dotnet-script**

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.19.10-x64

**Comment by filipw** [comment]
the latest version support .NET Core 3 now

**Comment by ghesketh** [comment]
dotnet-script 0.52.0 is still not working for me on Linux:

**dotnet --list-runtimes**                                   
```
Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
**dotnet tool list -g** 
```
Package Id         Version      Commands     
---------------------------------------------
dotnet-script      0.52.0       dotnet-script
```

**dotnet-script**
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.19.10-x64

```
Am I doing something wrong?

**Comment by seesharper** [comment]
could you do a `dotnet --info`. Remember that dotnet-script also needs the dotnet SDK to work

**Comment by ghesketh** [comment]
**dotnet --info**
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by seesharper** [comment]
And a `dotnet script --info` just to make sure that we have all the info:)

**Comment by ghesketh** [comment]
**dotnet script --info**
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.19.10-x64
```

**Comment by seesharper** [comment]
dotnet-script is shipped as both as a .Net Core 2.1 and a .Net Core 3.1 app. dotnet-script is installed based on the currently installed runtime. Could it be that you installed dotnet-script having 2.1 installed and then later installed 3.1 and also had 2.1 removed?

You could also do a `which dotnet-script` so that we are sure you are running from the tools folder

**Comment by 0xack13** [comment]
While I'm using `v0.52.0`, I had the same compatiblity issue with dotnet `3.1.1` as it's the only and default dotnet version in my Linux box. I was able to resolve this issue by modifying the `dotnet-script.runtimeconfig.json` [1] manually to point to `3.1` instead od `2.1`, as an example:
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.1"
    }
  }
}
```

[1] `/usr/local/lib/dotnet-script/dotnet-script.runtimeconfig.json`
