### ISSUE TITLE
Suggestion: use #load to include also remote .csx scripts

### ISSUE THREAD

**Issue by dmantovani73** [filipw/dotnet-script#535]
As far as I know, #load can be used to include local .csx files or remote nuget script packages but it's not able to load remote .csx files (hosted for example as a Gist).

Usage:
`#load "https://gist.githubusercontent.com/seesharper/5d6859509ea8364a1fdf66bbf5b7923d/raw/0a32bac2c3ea807f9379a38e251d93e39c8131cb/HelloWorld.csx"`

or

`#load "https://tinyurl.com/y8cda9zt"`

**Comment by dmantovani73** [comment]
[Implementing custom #load behavior in Roslyn scripting](https://www.strathweb.com/2016/06/implementing-custom-load-behavior-in-roslyn-scripting/)

**Comment by filipw** [comment]
thanks - that's my blog post 😀

However this will not be implemented here. We avoided this by design because we want to keep `#load` scoped to only loading CSX files or nuget packages. The goal is for dotnet-script to be a standard based script runner (with the #load behavior as defined by the compiler team) - and this behavior would be a deviation from that.

**Comment by dmantovani73** [comment]
Ok Filip, thank you. I'm already using .csx scripts on production
environments, I wish to congratulate, this is really a great work!

Il giorno mar 28 apr 2020 alle ore 10:52 Filip W <notifications@github.com>
ha scritto:

**Comment by filipw** [comment]
we used to have that feature (a similar one) in scriptcs but after learning from that I now would like to avoid that again.
by creating a script package you can achieve a similar result though.

thanks a lot

**Comment by atifaziz** [comment]
> we used to have that feature (a similar one) in scriptcs but after learning from that I now would like to avoid that again.

@filipw Hey, mind sharing the lesson(s) you learned that you think would be a mistake to repeat? I can imagine security being a concern.
