### ISSUE TITLE
Execution cache file is per script folder leading to error when running scripts in parallel

### ISSUE THREAD

**Issue by mungojam** [filipw/dotnet-script#540]
I'm using dotnet script for some scripts which I run in parallel. Both scripts are in the same folder, but unless I turn off caching, this leads to a clash on the common cache file `script.dll`:

> The process cannot access the file 'c:\somewhere\scripts\execution-cache\script.dll' because it is being used by another process.

The first script to get there works fine, but the 2nd fails because it tries to use the cache at the same time.

~It works if I use `--no-cache` but I would rather not.~

**Comment by mungojam** [comment]
Oddly, it doesn't even work when I use `--no-cache`:

> dotnet script --no-cache .\somewhere\configure-backend.csx 
> The process cannot access the file 'C:\Users\jenkins\AppData\Local\Temp\dotnet-script\C\somewhere\build-scripts\execution-cache\script.dll' because it is being used by another process.

**Comment by seesharper** [comment]
Hi @mungojam 

The reason it probably won't work even with the `--no-cache` option is that we always run the script from a compiled script (script.dll).

That being said, the cache should definitely handle executing two scripts in parallell from the same folder. Looking into it👍

**Comment by mungojam** [comment]
I've just spotted https://github.com/filipw/dotnet-script/issues/507 which is related.

I'm planning on submitting a PR for this one first though, using the filename in the temporary folder path if that makes sense?

**Comment by kuacci** [comment]
Is it possible to implement an abstraction layer of file system just like what scriptcs did?

**Comment by mganss** [comment]
A workaround is to set `DOTNET_SCRIPT_CACHE_LOCATION` to a separate directory for each of the scripts you are running in parallel.

**Comment by mungojam** [comment]
Aha! Neat idea, thanks. I can then put the cache within the build workspace
too so it's easier to find and archive as needed for build diagnostics

**Comment by mungojam** [comment]
Fixed by #596
