### ISSUE TITLE
Error after I added an environment variable

### ISSUE THREAD

**Issue by d0wser** [filipw/dotnet-script#549]
I added the environment variable 'NUGET_PACKAGES'. 
Now I get an error when I try to execute my code: "Unable to restore packages from 'C:\Users\d0wser\AppData\Local\Temp\dotnet-script\g\PuppeteerSharpTest\netcoreapp3.1\script.csproj'. Make sure that all script files contains valid NuGet references". What do I need to do to fix it? Is there a seetings file for DotNet-script I need to edit? Make changes to the registry?
Please help!

**Comment by seesharper** [comment]
@d0wser  Could you run the script with the debug option like this `dotnet script yourscript.csx --no-cache --debug` ?

**Comment by d0wser** [comment]
Thanks for helping out!

I can report that I'm able to run the script after reinstalling vscode, but I haven't managed to get OmniSharp to find the NuGet-dependencies. The NuGet environment variables NUGET_PACKAGES, NUGET_HTTP_CACHE_PATH and NUGET_PLUGINS_CACHE_PATH are all set to absolute paths. The output from executing "dotnet-script main.csx --no-cache --debug" is enclosed below:

G:\PuppeteerSharpTest>dotnet-script main.csx --no-cache --debug
dbug: Dotnet.Script.Core.Commands.ExecuteScriptCommand[0]
      The script G:\PuppeteerSharpTest\main.csx was executed with the '--no-cache' flag. Skipping cache.
info: Dotnet.Script.Core.ScriptCompiler[0]
      Current runtime is 'win'.
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Creating project file for G:\PuppeteerSharpTest\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing G:\PuppeteerSharpTest\main.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptParser[0]
      Parsing G:\PuppeteerSharpTest\log.csx
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      Project file saved to C:\ProgramData\dotnet-script\cache\dotnet-script\G\PuppeteerSharpTest\netcoreapp3.1\script.csproj
dbug: Dotnet.Script.DependencyModel.ProjectSystem.ScriptProjectProvider[0]
      <?xml version="1.0" encoding="utf-8"?>
      <Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
          <OutputType>Exe</OutputType>
          <TargetFramework>netcoreapp3.1</TargetFramework>
          <LangVersion>latest</LangVersion>
        </PropertyGroup>
        <ItemGroup>
          <PackageReference Include="ini-parser" Version="2.5.2" />
          <PackageReference Include="PuppeteerSharp" Version="2.0.3" />
          <PackageReference Include="HtmlAgilityPack" Version="1.11.24" />
        </ItemGroup>
        <Target Name="RecordReferencePaths" AfterTargets="AfterResolveReferences">
          <WriteLinesToFile File="$(OutputPath)/ReferencePaths.txt" Lines="@(ReferencePath)" />
        </Target>
      </Project>
dbug: Dotnet.Script.DependencyModel.Context.DotnetRestorer[0]
      Restoring C:\ProgramData\dotnet-script\cache\dotnet-script\G\PuppeteerSharpTest\netcoreapp3.1\script.csproj using the dotnet cli. RuntimeIdentifier : win10-x64 NugetConfigFile: C:\Users\d0wser\AppData\Roaming\NuGet\NuGet.Config
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      Executing 'dotnet restore "C:\ProgramData\dotnet-script\cache\dotnet-script\G\PuppeteerSharpTest\netcoreapp3.1\script.csproj" -r win10-x64
 --configfile "C:\Users\d0wser\AppData\Roaming\NuGet\NuGet.Config"'
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        Determining projects to restore...
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
      C:\ProgramData\dotnet-script\cache\dotnet-script\G\PuppeteerSharpTest\netcoreapp3.1\script.csproj : warning NU1701: Package 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
dbug: Dotnet.Script.DependencyModel.Process.CommandRunner[0]
        All projects are up-to-date for restore.
dbug: Dotnet.Script.DependencyModel.Context.ProfiledRestorer[0]
      Restoring C:\ProgramData\dotnet-script\cache\dotnet-script\G\PuppeteerSharpTest\netcoreapp3.1\script.csproj took 1529ms
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Configuration/Optimization mode: Debug
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Suppressed diagnostic CS1701: G:\PuppeteerSharpTest\main.csx(27,11): warning CS1701: Assuming assembly reference 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' used by 'PuppeteerSharp' matches identity 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' of 'Newtonsoft.Json', you may need to supply runtime policy
dbug: Dotnet.Script.Core.ScriptCompiler[0]
      Suppressed diagnostic CS1701: G:\PuppeteerSharpTest\main.csx(145,21): warning CS1701: Assuming assembly reference 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'PuppeteerSharp' matches identity 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.Extensions.Logging.Abstractions', you may need to supply runtime policy

**Comment by filipw** [comment]
if the script works, but OmniSharp has troubles, please post your OmniSharp log (after setting "omnisharp.loggingLevel": "debug" in VS Code)

**Comment by d0wser** [comment]
Setting the logging level to 'Debug' generated quite a lot of information. I've enclosed the output in a text file. Thanks for helping me!
[OmniSharp_Log.txt](https://github.com/filipw/dotnet-script/files/4866168/OmniSharp_Log.txt)

**Comment by filipw** [comment]
according to your log it's the same issue as here https://github.com/filipw/dotnet-script/issues/531#issuecomment-646664156

dotnet-script nuget packages support needs to be separately enabled in OmniSharp.

**Comment by seesharper** [comment]
You can do a `dotnet script init` in your script folder. That should take care of business 👍

**Comment by d0wser** [comment]
Thanks to both of you!
Everything seems to be working now!
