### ISSUE TITLE
Load once directive

### ISSUE THREAD

**Issue by Acmion** [filipw/dotnet-script#553]
I'd like to have similar functionality as PHP's `include_once` in `dotnet-script`. 

For those not familiar with PHP, the function `include` is the equivalent of `#load` in `dotnet-script`.

Currently we can `#load` files, but this will cause problems in some cases, for example, static classes (among others). Implementing `#load-once` would solve these issues.

**My specific scenario**

Scripts:
A.csx, which `#load ./Shared.csx` 
B.csx, which `#load ./Shared.csx`
Shared.csx, contains a static class definition
All.csx, a script that should execute A then B

All.csx will not execute in this scenario due to the static class in Shared.csx being declared twice.

**Comment by seesharper** [comment]
The `#load` directive is not specific to `dotnet script`. Rather is is defined by the Roslyn scripting engine. Adding a new directive is not something that can be done in `dotnet-script`. It has to be a part of the compiler platform (Roslyn). 
If you have suggestions as to how to add new features to Roslyn, you need to address this repo. 
https://github.com/dotnet/roslyn
