### ISSUE TITLE
Eval command doesn't work properly

### ISSUE THREAD

**Issue by Alvin-Seville** [filipw/dotnet-script#558]
[Scripting.zip](https://github.com/filipw/dotnet-script/files/4834841/Scripting.zip)

When I bother execute this command:
```
dotnet script eval main.csx
```
I get an error:
```
(1,1): error CS0103: The name 'main' does not exist in the current context
```
Is it my error or bug?

**Comment by filipw** [comment]
eval is supposed to be used when passing inline C# code, not with a script file. to run a script just invoke `dotnet script main.csx‘
