### ISSUE TITLE
Performance doubt

### ISSUE THREAD

**Issue by GF-Huang** [filipw/dotnet-script#563]
Is the csx file interpret or compile? 

I had test by a `O(n log n)` algorithm with `20,000` data point. 
- The standard .net core console takes about `45` seconds.
- The csx which run by dotnet-script takes about `64` seconds.

Both are run in `Release` mode, same code.

![image](https://user-images.githubusercontent.com/4510984/87333291-7f89cb00-c56f-11ea-9708-4a9c4234fecd.png)

**Comment by filipw** [comment]
it's compiled, cached and run.
second run would be fast

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/87338970-823cee00-c578-11ea-8e51-275b57830f2c.png)

This is my code, if it's compiled I don't think the `Stopwatch.Elapsed` will includes the compile time.

And I run it 3 times, but same result, it looks far from `45` seconds.

![image](https://user-images.githubusercontent.com/4510984/87339887-ddbbab80-c579-11ea-9d74-aba942ae88ea.png)

**Comment by filipw** [comment]
yeah you are only measuring execution time. there is not interpreted C# support in the C# compiler. scripting here is just a syntactic trick

**Comment by GF-Huang** [comment]
So what caused the performance difference?

**Comment by filipw** [comment]
you should open an issue in the compiler repository https://github.com/dotnet/roslyn

we are only users of the compiler API and the execution performance difference here is not cause by dotnet-script but some behavior of the compiler (or the runtime)
