### ISSUE TITLE
"global.json" interferes with "dotnet restore" of script

### ISSUE THREAD

**Issue by atifaziz** [filipw/dotnet-script#571]
If you try to run a C# script from a folder that contains a `global.json` to pin to a .NET Core SDK version then `dotnet restore` that's executed by `dotnet-script` may fail (depending on the SDK version) to restore packages.

PowerShell steps to reproduce:

1. Create a blank directory and set it as the current directory
2. Create a `global.json` file that pins to .NET Core SDK 3.0.100:
   ```
   Set-Content global.json '{ "sdk": { "version": "3.0.100" } }'
   ```
3. Evaluate a script, e.g.:
   ```
   dotnet script eval //
   ```

At the end of step 3, you should get an error along the lines of:

```
Unable to restore packages from 'C:\Users\johndoe\AppData\Local\Temp\dotnet-script\A\temp\Eval\interactive\interactive\netcoreapp3.1\script.csproj'. Make sure that all script files contains valid NuGet references
```

Evaluating a script that's just a comment, as in the last step above, is the simplest way to reproduce this error but the issue applies equally to running a script:

```
❯ Set-Content global.json '{ "sdk": { "version": "3.0.100" } }' # pin SDK
❯ Set-Content test.csx $null # create a blank script file
❯ dotnet script test.csx
Unable to restore packages from 'C:\Users\johndoe\AppData\Local\Temp\dotnet-script\A\temp\netcoreapp3.1\script.csproj'. Make sure that all script files contains valid NuGet references
```

**Comment by atifaziz** [comment]
I should add that the bigger problem here is that the success/failure of running a script will depend on the directory your are in and whether it has a compatible `global.json`. The success/failure can therefore be completely arbitrary.

**Comment by seesharper** [comment]
I have seen this on a couple of occasions myself and I think it might be because `dotnet restore` is executed with the script folder as the current working directory. I better approach would probably be to set the working directory to the same folder as the generated csproj file located in the temp folder.

**Comment by atifaziz** [comment]
Can we mark this as a bug then?

> I better approach would probably be to set the working directory to the same folder as the generated csproj file located in the temp folder.

Right except I think it breaks several tests that assert assumptions about relative paths.

**Comment by seesharper** [comment]
I'll have a look
