### ISSUE TITLE
How to suppress error NU1605 in my script

### ISSUE THREAD

**Issue by yan0lovesha** [filipw/dotnet-script#574]
I need to reference package (Microsoft.Azure.Cosmos.Table 1.0.7) in my script. But this version of package contains a mismatched dependency versions. 
When I try to use dotnet script "myscript.csx" --no-cache --debug to see the logs, I found the information as below:

```
error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.

error NU1605:  script -> Microsoft.Azure.Cosmos.Table 1.0.7 -> Microsoft.Azure.DocumentDB.Core 2.10.0 -> System.Net.NetworkInformation 4.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)

error NU1605:  script -> Microsoft.Azure.Cosmos.Table 1.0.7 -> Microsoft.Azure.DocumentDB.Core 2.10.0 -> System.Net.NameResolution (>= 4.0.0)

error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.

error NU1605:  script -> Microsoft.Azure.Cosmos.Table 1.0.7 -> Microsoft.Azure.DocumentDB.Core 2.10.0 -> NETStandard.Library 1.6.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)

error NU1605:  script -> Microsoft.Azure.Cosmos.Table 1.0.7 -> Microsoft.Azure.DocumentDB.Core 2.10.0 -> System.Net.NameResolution (>= 4.0.0)

```

In my VS project, I can workaround this by adding <NoWarn>NU1605</NoWarn> to the project file. 

Is there a way I can suppress this error in dotnet script?

**Comment by seesharper** [comment]
Could you post a minimal repro of the script itself?

**Comment by seesharper** [comment]
This checks out fine on my end :)


```
#!/usr/bin/env dotnet-script
#r "nuget:Microsoft.Azure.Cosmos.Table, 1.0.7"

using Microsoft.Azure.Cosmos.Table;

Console.WriteLine("Hello world!");
```

Could you also do a `dotnet script --info` and dump the result here?

**Comment by yan0lovesha** [comment]
This is a minimum repro:

```
#r "nuget:Newtonsoft.Json, 12.0.3"
#r "nuget:Microsoft.Azure.Cosmos.Table, 1.0.7"

return 0;
```

And the --info returns following info:

```
dotnet script --info
Version             : 0.53.0
Install location    : C:\Users\neilyan\.dotnet\tools\.store\dotnet-script\0.53.0\dotnet-script\0.53.0\tools\netcoreapp3.1\any
Target framework    : netcoreapp3.1
.NET Core version   : 3.1.5
Platform identifier : win
Runtime identifier  : win10-x64

```

**Comment by yan0lovesha** [comment]
Seems like NU1605 is not the root cause. Because there is no problem if I only reference Microsoft.Azure.Cosmos.Table.

**Comment by seesharper** [comment]
Probably our old friend `Newtonsoft.Json` again. I'll have a look

**Comment by seesharper** [comment]
Try this 
```
#r "nuget:System.Net.NameResolution, 4.3.0"
#r "nuget:Newtonsoft.Json, 12.0.3"
#r "nuget:Microsoft.Azure.Cosmos.Table, 1.0.7"
```

**Comment by seesharper** [comment]
If you see in the error message `error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.` 

Referencing the higher version of the package directly usually fixes the problem

**Comment by yan0lovesha** [comment]
This works. Could you teach me what does Newtonsoft.Json do here to make this issue as a blocker? Without referencing Newtonsoft.Json, this issue is just ignored.

**Comment by seesharper** [comment]
Well, it is because of a mismatch between transient dependencies during restore. I think I'll just add a link to rhe docs in this case. 😀 They do a much better job at explaining this than I can 😀 https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605

**Comment by yan0lovesha** [comment]
Thanks a lot.
