### ISSUE TITLE
Allow dependency specification using csproj

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#59]
Since `project.json` is effectively a dead technology we should be able to specify dependencies using csproj.

Note this is orthogonal from https://github.com/filipw/dotnet-script/issues/58 which only deals with migrating this actual project to csproj, not the dependency specification

**Comment by masaeedu** [comment]
@filipw Might be useful to structure this as something that hooks into the MSBuild project system as a `<DotNetCliToolReference />`. See for example https://github.com/pgroene/dotnet-allversions

**Comment by filipw** [comment]
yep, this is exactly what it is today already, except in the `project.json` world not `csproj` world

**Comment by seesharper** [comment]
What would it take to move from project.json to csproj. Microsoft.DotNet.ProjectSystem is probably dying along with project.json? 

Does MSBuild provide something similar to this?
```
var projectExporter = runtimeContext.CreateExporter("Release");
var projectDependencies = projectExporter.GetDependencies();
```

**Comment by filipw** [comment]
no, unfortunately not. we would need to do everything by hand. Literally the same stuff that happens here https://github.com/OmniSharp/omnisharp-roslyn/blob/dev/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs#L94

**Comment by seesharper** [comment]
Okay, I don't want to sick my nose into that rabbit hole just yet :)

Do you know of any class in Microsoft.DotNet.ProjectSystem that serializes to project.json?

In other words, is there a class I can instantiate, populate a collection of NuGet package dependencies and write it out as project.json?

**Comment by filipw** [comment]
dupe of #88
