### ISSUE TITLE
nuget packages not loading 

### ISSUE THREAD

**Issue by rsquarev** [filipw/dotnet-script#601]
Hi there,
I decided to use dotnet script instead of linqpad as most of my development is in vscode. so I started with `dotnet script init`.
First I got issue with `.Net Script Debug`. I figured that vscode is looking for `.vscode` folder in parent of `.csx` directory.
Now, I am at `main.csx` with following code. Inteli-sense doesn't recognize namespace `System.Net.Http`. Obviously omnisharp/msbuild is not restoring packages. I also tried `Nuget.Config` in directory where `main.csx` is, and also its parent directory. `Nuget.config` may be irrelevant as `msbuild` issue needs to be resolved first.

```csharp
#r "nuget: System.Net.Http, 4.3.4"
using System.Net.Http;
var client=new HttpClient();
Console.WriteLine("Hello world!");
```

As I see in other issues, I changed omnisharp logging level to `trace`. I got lot of trace, but not sure what causing my issue. 
I have 3 locations for msbuild. 2019, 2017 (installed from chocolatey installation) and stand alone.
I also tried to change omnisharp.json to override msbuild path like below, which didn't make any difference.

```json
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "net5.0"
  },
"msbuild": {
  "MSBuildSdksPath":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin",
  "enabled": true,
  }
}
```
I am uploading the omnisharp log here. its quite big.
[omnisharp.log](https://github.com/filipw/dotnet-script/files/5711951/omnisharp.log)

I appreciate your help!!

**Comment by filipw** [comment]
according to the log the your `omnisharp.json` is not discovered. 
Is it located at the root of the workspace you are opening in VS Code?

The log shows that instead of `net5.0`, the CSX scripts are offered with .NET 4.6.1 desktop mode, without nuget support.

```
[info]: OmniSharp.Script.ScriptContextProvider
        Searching for compilation dependencies with the fallback framework of 'net461'.
[fail]: OmniSharp.Script.ScriptContextProvider
        Failed to resolve compilation dependencies
[info]: OmniSharp.Script.ScriptContextProvider
        Unable to find dependency context for CSX files. Will default to non-context usage (Desktop CLR scripts).
```

**Comment by rsquarev** [comment]
Thanks for that insight @filipw. You are right about workspace. Now I moved `omnisharp.json` to workspace directory.
What version should I pick if `net5.0` is not supported. Here is my `dotnet --info`. I changed it to `netcore3.1` though.
it still fails.

```log
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Here is my project structure.
![image](https://user-images.githubusercontent.com/12549485/102544845-07be5000-407b-11eb-98b7-ec0daa0593b9.png)

Here is omnisharp.json
```json
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "netcore3.1"
  },
  "msbuild": {
    "MSBuildSdksPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin",
    "enabled": true
  }
}
```

Here is omnisharp log file again..
[omnisharp2.log](https://github.com/filipw/dotnet-script/files/5712214/omnisharp2.log)

**Comment by filipw** [comment]
The TFM for .NET Core 3.1 is `netcoreapp3.1` not `netcore3.1`.
Also, you should not set `MSBuildSdksPath` to VS 2017 as it uses MSBuild 15.9. 
The minimum MSBuild for .NET Core 3.1 is 16.3 and for .NET 5.0 is 16.8. Leaving this to default and letting OmniSharp choose is the best option.

**Comment by filipw** [comment]
one more thing, you don't need to pull `System.Net.Http` from NuGet - it's available there by default so you can just start using it directly

**Comment by rsquarev** [comment]
I was trying as an example for `System.Net.Http`. Originally I wanted to get `nuget: System.Net.Http.Json, 5.0.0`.

I tried with `netcoreapp3.1` as well. Now moved back to default `net5.0` and it doesnt complain about fallback to `net461`.
`script.csproj` also created in temp folder. However, no referenced package downloaded.

```log
[fail]: OmniSharp.Script.ScriptContextProvider
        Failed to resolve compilation dependencies
[info]: OmniSharp.Script.ScriptContextProvider
        Unable to find dependency context for CSX files. Will default to non-context usage (Desktop CLR scripts).
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Attempting to resolve 'System.Runtime'
[dbug]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        FAILURE: Could not locate 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\System.Runtime.dll'.
```

I am ok with any framework. just wanted the `#r "nuget: "`

**Comment by rsquarev** [comment]
I tried with a fresh workspace and it works with net5.0 flawless. I think `Nuget.Config` was the issue in my old setup also. After I remove that file, even old workspace works as intended. Thank you very much for your help @filipw.
