### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by AmSmart** [filipw/dotnet-script#603]
Are we getting .NET 5 support for this project? I don't think the effort should be much since  .net core 3.1 and .NET 5 are almost 100% API compatible. Nevertheless, I don't really know how this works so I can't estimate the effort. If clear steps are provided on  the migration, many folks like myself would be willing to help

**Comment by filipw** [comment]
it's already supported since day 1 of .NET 5.0, please install latest version 
https://www.strathweb.com/2020/11/dotnet-script-1-0-0-released-with-support-for-net-5-0-and-c-9/

**Comment by AmSmart** [comment]
Thanks for the quick reply. I have now updated my version of dotnet-script. My assumptions were based on the fact that the ``readme.md`` file didn't contain any information related to .NET 5
