### ISSUE TITLE
Native image cannot be loaded multiple times 

### ISSUE THREAD

**Issue by mal4k** [filipw/dotnet-script#61]
I am using dotnet-script for my project. And getting this Error msg:
> Native image cannot be loaded multiple times 

This Error also occurs on Linux (Debian), and I cannot use .net Framework because the project has to run on a raspberry.
I tried NETCore 1.0 and Dotnet.Script 0.7.0-beta too, same issue.
Everything else is working fine but as soon as "IPAdress.Parse("")" gets called outside of the Script (inside the .dll) the error will occure.
If I call "IPAdress.Parse("")" inside an async Task<>, it works fine.

Very Simple to reproduce:
```
//foo.csx
using ConsoleApp1;
var mc = new MyClass("127.0.0.1");
```

```
//project.json
{
  "dependencies": {
    "ConsoleApp1": "1.0.0-*"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  },
  "tools": {
    "Dotnet.Script": {
      "version": "0.8.0-beta",
      "imports": [
        "portable-net45+win8",
        "dnxcore50"
      ]
    },
  }
}
```
```
//MyClass.cs
using System.Net;

namespace ConsoleApp1
{
    public class MyClass
    {
        public MyClass(string ip)
        {
            var m_ip = IPAddress.Parse(ip);
        }
    }
}
```

```
//project.json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {
    "Verbosity": "1.0.0-*"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```
2 more fast questions:
1.
From the Read.me:
<NUGET_ROOT>\\Dotnet.Script\\0.7.0-beta\\lib\\netcoreapp1.0\\dotnet-script.deps.json
this file doesnt exist on my machine.
2. 
The Script looking for .dll's in the bin/Release instead of bin/Debug directory. Is there a way to change that?

**Comment by filipw** [comment]
> Everything else is working fine but as soon as "IPAdress.Parse("")" gets called outside of the Script (inside the .dll) the error will occure.
> If I call "IPAdress.Parse("")" inside an async Task<>, it works fine.

so you mean that if you call the method inside the script directly it works fine?

> From the Read.me: <NUGET_ROOT>\Dotnet.Script\0.7.0-beta\lib\netcoreapp1.0\dotnet-script.deps.json this file doesnt exist on my machine.

Try inside the `.tools` folder under nuget packages root (in your user folder)

> The Script looking for .dll's in the bin/Release instead of bin/Debug directory. Is there a way to change that?

you can pass `-conf Debug` to enforce Debug configuration

**Comment by filipw** [comment]
Also, at the moment dotnet-script doesn't support Net Core 1.1.0, so everything you have here should be downgraded to Net Core 1.0.1.

Net Core 1.1.0 will be supported as soon as #60 is merged

**Comment by mal4k** [comment]
Many thanks,
looking forward for the Net Core 1.1.0 support.

> so you mean that if you call the method inside the script directly it works fine?

Yes, partially...

Here are two scenarios where I get the mentioned Error-msg:
A)
```
//foo.csx
using System.Net;
var ip = IPAddress.Parse("127.0.0.1"); 
var myClass = new MyClass(ip);
```
```
//MyClass.cs (dll)
using System.Net;
    public class MyClass
    {
        public MyClass(IPAddress ip)
        {
            var m_ip =ip;
        }
    }
```
B)
```
//foo.csx
var myClass = new MyClass("127.0.0.1");
```
```
//MyClass.cs (dll)
using System.Net;
    public class MyClass
    {
        public MyClass(string ip)
        {
            var m_ip =IPAddress.Parse(ip);
        }
    }
```
When my .dll does not use IPAdress it works fine.
C)
```
//foo.csx
var ip = IPAddress.Parse("127.0.0.1"); 
```

As soon as I parse the ip to the .dll and do something with it there I get

> Native image cannot be loaded multiple times

My guess is that is loads the libs for IPAdress from a different location in the script then in the dll dependecies.

**Comment by filipw** [comment]
Thanks, that's very helpful, I'll have a look

**Comment by mal4k** [comment]
Ok cool,
so far I've tested it on Debian, Windows 7, and Windows 10 and I also noticed that everything inside the "System.Net;" namespace produces the error.
It's fine as long its only in the Script, but not if it's inside the dependencies.
Same thing when I use the #r directive to import dll's instead of inside the project.json

`#r "C:\path\to\ConsoleApp1.dll"`

**Comment by seesharper** [comment]
We have just revisited this issue and it seems like it works as expected now. 

Console App

```
 public class MyClass
    {
        public MyClass(string ip)
        {
            var m_ip = IPAddress.Parse(ip);
            Console.WriteLine(m_ip);
        }
    }
```

Console App csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>

```

Script 

```
#! "netcoreapp2.0"
#r "c:/Github/ParseIp/bin/Debug/netcoreapp2.0/ParseIp.dll"

using ParseIp;

MyClass c = new MyClass("127.0.0.1");
Console.WriteLine("Hello world!");
```

output

```
$ dotnet script main.csx
127.0.0.1
Hello world!
```
