### ISSUE TITLE
Allow CancellationToken in Execute method

### ISSUE THREAD

**Issue by sean-mcl** [filipw/dotnet-script#612]
Hello,

I am currently trying to modify the scripts at runtime. If the script changes, the current execution of the script should be aborted.  Is this somehow possible in .NET 5.0?

I would like to have the ability to pass a CancellationToken to the Execute task.

Thanks for the cool library! 👍🏻

**Comment by filipw** [comment]
I can add cancellation, but it will not really work as you expect it.
In general aborting a script is not really possible (see the discussion here in the C# compiler repo https://github.com/dotnet/roslyn/issues/23145#issuecomment-345488071)

The best you could do would be to run the script as an external process and kill that process when you know "it's time" to do it.
