### ISSUE TITLE
Metadata file 'System.Data.Odbc' could not be found

### ISSUE THREAD

**Issue by stevenkc** [filipw/dotnet-script#619]
#r "nuget: System.Data.Odbc, 5.0.0"
#r "System"
#r "System.Data"
#r "System.Data.Odbc"

try to add the System.Data.Odbc to dotnet script
got this message "Metadata file 'System.Data.Odbc' could not be found"

**Comment by filipw** [comment]
```
#r "System"
#r "System.Data"
#r "System.Data.Odbc"
```

This syntax loads a DLL from GAC, which why the metadata cannot be found. 
I assume this is not what you are trying to do, since you also reference `System.Data.Odbc` from nuget.

**Comment by stevenkc** [comment]
#r "nuget: System.Data.Odbc, 5.0.0"
#r "System"
#r "System.Data"
#r "System.Data.Odbc"

using System;
using System.Data;
using System.Data.Odbc;

This is my code
