### ISSUE TITLE
No "depsfile" being generated in Nuget package

### ISSUE THREAD

**Issue by Sharpiro** [filipw/dotnet-script#62]
Hi, just got a .csx breakpoint to hit in VS Code using your tool, very cool stuff!

One issue I had though, was with the ```"--depsfile", "<NUGET_ROOT>\\Dotnet.Script\\0.7.0-beta\\lib\\netcoreapp1.0\\dotnet-script.deps.json"```

When I restore the dotnet-script nuget package, either 0.7.0-beta or 0.9.0-beta, the ```dotnet-script.deps.json``` does not exist at the above location where ```dotnet-script.dll``` is located, and the debugger would not run without a valid file being provided.

As a workaround I cloned and built locally and pointed to the ```dotnet-script.deps.json```file that gets generated with the build.

Thanks.

**Comment by filipw** [comment]
The deps file should be located under `.tools` -> `"<NUGET_ROOT>\\.tools\\Dotnet.Script\\0.7.0-beta\\lib\\netcoreapp1.0\\dotnet-script.deps.json"`.
I must have messed it up in the readme.

**Comment by filipw** [comment]
Here is a full working debug `launch.json` for OS X:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Script Debug",
            "type": "coreclr",
            "request": "launch",
            "program": "/usr/local/share/dotnet/dotnet",
            "args": [
                "exec", 
                "--additionalprobingpath", 
                "/Users/filip/.nuget/packages", 
                "--depsfile", 
                "/Users/filip/.nuget/packages/.tools/Dotnet.Script/0.9.0-beta/netcoreapp1.0/Dotnet.Script.deps.json", 
                "/Users/filip/.nuget/packages/Dotnet.Script/0.9.0-beta/lib/netcoreapp1.0/dotnet-script.dll", 
                "${workspaceRoot}/foo.csx",
                "-d"],
            "cwd": "${workspaceRoot}",
            "externalConsole": false,
            "stopAtEntry": true,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}
```

**Comment by Sharpiro** [comment]
Yep found it under ```.tools```, thanks.  You can close this when you're ready.

**Comment by filipw** [comment]
thanks! I'll update the readme 👍
