### ISSUE TITLE
ODBC need runding under x86

### ISSUE THREAD

**Issue by stevenkc** [filipw/dotnet-script#620]
System.Data.Odbc.OdbcException (0x80131937): ERROR [IM014] [Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application

How to run dotnet script xxx.csx under the 32bit runtime?

Can I run it like "dotnet script script.csx -r win-x86"?

**Comment by filipw** [comment]
it is not supported in a script mode, but you can compile into an exe.
For example the following script:

```
Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture);
```

would return `X64` when running as `dotnet script main.csx`:

```
C:\code\csx\odbc>dotnet script main.csx
X64
```

But you could compile it:

```
C:\code\csx\odbc>dotnet script publish main.csx -r win-x86
Published C:\code\csx\odbc\main.csx (executable) to C:\code\csx\odbc\publish\win-x86
```

then when invoking the compile `main.exe` would print `x86`:

```
C:\code\csx\odbc>publish\win-x86\main.exe
X86
```
