### ISSUE TITLE
Can't reference nuget packages

### ISSUE THREAD

**Issue by michaelalpine** [filipw/dotnet-script#632]
I have a console app I am trying to publish as a stand alone thing but it references some third party stuff. So far I've tried this but it doesn't seem to be working

#r "nuget:Newtonsoft.Json -Version 13.0.1"
#r "nuget:Countersoft.Gemini.Api -Version 1.0.2"
#r "nuget:Countersoft.Gemini.Library -Version 1.0.1"
using System;
using System.IO;
using System.Text;
using Countersoft.Gemini.Api;
using Countersoft.Gemini.Commons.Dto;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;

I'm trying to build via dotnet script publish "MyProgram.csx"

The error I get is 
C:\Websites-Alpine\DeploymentHelper\CSX>dotnet script publish "Program.csx"
C:\Websites-Alpine\DeploymentHelper\CSX\Program.csx(4,7): error CS0246: The type or namespace name 'Countersoft' could not be found (are you missing a using directive or an assembly reference?)

I don't think it is referencing what it needs to but am not sure how to proceed. Thanks

**Comment by filipw** [comment]
the syntax for adding nuget references is `#r "nuget:Countersoft.Gemini.Library, 1.0.1"`
