### ISSUE TITLE
How can I use this tool in code?

### ISSUE THREAD

**Issue by oliver021** [filipw/dotnet-script#643]
What I need is a method or the way to use a string like c # code to execute at runtime. In other words, an endpoint sends c # code and it must be executed. I would greatly appreciate the help. Greetings

**Comment by ironsm4sh** [comment]
You may want to take a look at https://github.com/dotnet/interactive
The sample [simple-fsharp-console](https://github.com/dotnet/interactive/blob/main/samples/simple-fsharp-console/Program.cs) dynamically loads F# code as user input and then executes it. \
You could do the same for C# by using the `CSharpKernel` instead.
