### ISSUE TITLE
C# language version issue

### ISSUE THREAD

**Issue by intrasight** [filipw/dotnet-script#652]
I am getting an error when I try to use a 'using' statement without braces. I know this is a c# language feature. 
I am using dotnet-script v1.3.1. Is there a command to tell me the compiler version?

**Comment by seesharper** [comment]
Is it a runtime error or only in Vs Code.?

**Comment by intrasight** [comment]
Compile error

**Comment by intrasight** [comment]
Statement 

    using var jsonDoc = JsonDocument.Parse(responseBody2);

Getting

    error CS1002: ; expected
    error CS0103: The name 'jsonDoc' does not exist in the current context

On that line

**Comment by intrasight** [comment]
It was a Roslyn issue. See https://stackoverflow.com/questions/70610365/why-am-i-getting-an-error-with-this-using-statement-without-brackets-net-6

placing curly braces around my script made the compiler happy.
