### ISSUE TITLE
[Question] Possible to access environment variable in #load?

### ISSUE THREAD

**Issue by MostHated** [filipw/dotnet-script#655]
Hey there,
    I just had a quick question of if it might be at all possible to access environment variables within the #load portion of a script? I wanted to put some frequently used items within a folder in $HOME (~/.csx). I tried to see if I could use either of the following:

```cs
#load "~/.csx/shell.csx"
#load "$HOME/.csx/shell.csx"
```
It did not seem to like that. Is there a way to accomplish this, either by pulling an env var, or perhaps setting an external shared path config value somewhere that all scripts might be able to get to, or do I just have to hard code that path?

Thanks,
-MH

**Comment by filipw** [comment]
This is currently not possible. The path in the load directive is only resolved by dotnet-script if takes the `#load "nuget:{package}, {version}"` form and by the Roslyn compiler otherwise.
