### ISSUE TITLE
Question: can I use extension methods?

### ISSUE THREAD

**Issue by kasimier-vireq** [filipw/dotnet-script#668]
I tried to define an extension methods but I'm getting the following error (German; meaning that extension methods need to be defined at top-level, but this is a nested class):

"error CS1109: Die Erweiterungsmethoden müssen in statischen Klassen auf oberster Ebene definiert werden. "Extensions" ist eine geschachtelte Klasse."

**Comment by seesharper** [comment]
It means that your extension methods must be top-level methods. 

Example. 

```
public static string GetFirstFiveCharacters(this string value)
{
    return value[..5];
}
```

**Comment by kasimier-vireq** [comment]
Yes, but the script thingy wraps all top-level definitions implicitly:
![image](https://user-images.githubusercontent.com/85169537/157436148-437b4f4d-437f-4065-a42d-e62bfcd69294.png)

**Comment by kasimier-vireq** [comment]
Ah, now I get what you meant. The static extension class must be omitted. Great, thanks!
![image](https://user-images.githubusercontent.com/85169537/157436479-e4cf558a-2583-43d0-be03-6a96eb504b37.png)
