### ISSUE TITLE
Default `using` statements

### ISSUE THREAD

**Issue by DanJBower** [filipw/dotnet-script#669]
What are the default using statements in a csx file?

`Console.WriteLine("Hello World");` in a csx file on it's own works, so I figured `using System` is one. I was wondering if there are any others?

**Comment by seesharper** [comment]
https://github.com/filipw/dotnet-script/blob/f562a6c87c545701df16fce1aee7e125f711d09d/src/Dotnet.Script.Core/ScriptCompiler.cs#L42

**Comment by DanJBower** [comment]
> https://github.com/filipw/dotnet-script/blob/f562a6c87c545701df16fce1aee7e125f711d09d/src/Dotnet.Script.Core/ScriptCompiler.cs#L42

Thanks very much
