### ISSUE TITLE
Improve implicit references 

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#73]
Should mimic CSI. 
At the moment things are very limited without NetStandard.Library reference.

**Comment by adamralph** [comment]
Has CSI changes much with VS 2017? I still need to take a look...

**Comment by filipw** [comment]
no, not at all

**Comment by adamralph** [comment]
😢

**Comment by filipw** [comment]
This is related to #102

**Comment by filipw** [comment]
This can be closed now.
