### ISSUE TITLE
Take on Roslyn 3 alpha dependency

### ISSUE THREAD

**Issue by filipw** [filipw/dotnet-script#77]
We'd like to be able to leverage https://github.com/dotnet/roslyn/pull/16489 as soon as possible, so we should move to latest Roslyn (nightlies or self-built) ASAP.
This will improve debugging experience.

**Comment by seesharper** [comment]
Will you be taking a PR on this?

**Comment by filipw** [comment]
sure, why not! I was thinking to simply internalize the new assemblies

Am 05.04.2017 6:49 nachm. schrieb "Bernhard Richter" <
notifications@github.com>:

**Comment by seesharper** [comment]
https://github.com/filipw/dotnet-script/pull/78 ready for review :)

**Comment by filipw** [comment]
Fixed by #78
