### ISSUE TITLE
Move to csproj?

### ISSUE THREAD

**Issue by seesharper** [filipw/dotnet-script#88]
Did a quick test with reading the runtime dependencies from 'project.assets.json'

Could we do something like this to move to cproj?

As you can see the code is all hacky, but it works in the same way as the ProjecxExporter

PS: No idea what I am doing :)

```
private IEnumerable<string> GetRuntimeDependenciesFromDepsFile()
{                        
    var runtimeDepedencies = new List<string>();

    var pathToDepsFile = @"C:\Github\scripttest\obj\project.assets.json";
    using (FileStream fs = new FileStream(pathToDepsFile, FileMode.Open, FileAccess.Read))
    {
        using (var reader = new DependencyContextJsonReader())
        {
            var context = reader.Read(fs);
            
            var runtimeLibraries = context.RuntimeLibraries;                    
            foreach (var runtimeLibrary in runtimeLibraries)
            {                       
                if (runtimeLibrary.RuntimeAssemblyGroups.Count > 0)
                {                            
                    var path = runtimeLibrary.Path;
                    foreach (var runtimeLibraryRuntimeAssemblyGroup in runtimeLibrary.RuntimeAssemblyGroups)
                    {
                        if (runtimeLibraryRuntimeAssemblyGroup.Runtime == "win" ||
                            runtimeLibraryRuntimeAssemblyGroup.Runtime == "")
                        {
                            path = Path.Combine(path, runtimeLibraryRuntimeAssemblyGroup.AssetPaths[0]);
                            if (!path.EndsWith("_._"))
                            {
                                runtimeDepedencies.Add(path);
                            }
                            
                        }
                    }
                }
            }

        }
    }
    return runtimeDepedencies;
}
```

**Comment by filipw** [comment]
This is great. I think we can support both for the time being for the sake of sanity - but would you be willing to open a PR or should I? 😄

**Comment by seesharper** [comment]
Sorry for the late reply. Currently in vacation mode and will be for another couple of weeks. If you want to get the ball moving before that you can take a look here. I have this CSX project that is basically nothing but a place where I experiment with scripting stuff :) 
https://github.com/seesharper/csx/blob/master/src/RuntimeDependencyResolver.cs

**Comment by seesharper** [comment]
I've started to look into this a bit more and we can easily support both project.json and csproj simultaneously. The best approach would probably be to use csproj behind the scenes for project-less contexts. Then we would no longer rely on NuGet350 to resolve Nuget Packages. All we need for package resolving at the execution side (dotnet script) is the dotnet cli. Having it work with an "user defined" csproj file is a step further down the road as it would require changes in omnysharp-roslyn. I doing a spike now on how to get csproj support into dotnet script for project-less contexts.

**Comment by seesharper** [comment]
The goal is to have this script work on Windows and *nix platforms.

```
#r "nuget:Microsoft.Data.SQLite, 1.1.1"
using Microsoft.Data.Sqlite;

using (var connection = new SqliteConnection("Data Source=:memory:"))
{
    connection.Open();
}
```
This involves loading native libraries as well as assembly redirecting.
If we can load and execute this script, we should be able to consume just about any package.

**Comment by seesharper** [comment]
Covered by the 0.13.0 release
