### ISSUE TITLE
Support .NETCoreApp 1.1

### ISSUE THREAD

**Issue by codeape2** [filipw/dotnet-script#89]
I wonder how much effort is needed to support .NETCoreApp 1.1?

**Comment by filipw** [comment]
yeah should be straight forward - are you going to send a PR (I saw you forked 😄)

**Comment by codeape2** [comment]
Will give it a try.

How about supporting .csproj - do you have any ideas about how to do that? I built a netcoreapp1.1 version, but when running, it complained about missing project.json file.
